/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type DashboardBlocksAPI interface {

	/*
	CreateDashboardBlock Create a new block in a dashboard

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param dashboardId Dashboard ID
	@return ApiCreateDashboardBlockRequest
	*/
	CreateDashboardBlock(ctx context.Context, dashboardId string) ApiCreateDashboardBlockRequest

	// CreateDashboardBlockExecute executes the request
	//  @return CreateAttributeItem201Response
	CreateDashboardBlockExecute(r ApiCreateDashboardBlockRequest) (*CreateAttributeItem201Response, *http.Response, error)

	/*
	DeleteDashboardBlock Delete a dashboard block

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param dashboardId Dashboard ID
	@param blockId Block ID
	@return ApiDeleteDashboardBlockRequest
	*/
	DeleteDashboardBlock(ctx context.Context, dashboardId string, blockId string) ApiDeleteDashboardBlockRequest

	// DeleteDashboardBlockExecute executes the request
	DeleteDashboardBlockExecute(r ApiDeleteDashboardBlockRequest) (*http.Response, error)

	/*
	GetDashboardBlock Get a dashboard block by ID

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param dashboardId Dashboard ID
	@param blockId Block ID
	@return ApiGetDashboardBlockRequest
	*/
	GetDashboardBlock(ctx context.Context, dashboardId string, blockId string) ApiGetDashboardBlockRequest

	// GetDashboardBlockExecute executes the request
	//  @return DashboardBlockResponse
	GetDashboardBlockExecute(r ApiGetDashboardBlockRequest) (*DashboardBlockResponse, *http.Response, error)

	/*
	ListDashboardBlocks List all blocks in a dashboard

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param dashboardId Dashboard ID
	@return ApiListDashboardBlocksRequest
	*/
	ListDashboardBlocks(ctx context.Context, dashboardId string) ApiListDashboardBlocksRequest

	// ListDashboardBlocksExecute executes the request
	//  @return ListDashboardBlocks200Response
	ListDashboardBlocksExecute(r ApiListDashboardBlocksRequest) (*ListDashboardBlocks200Response, *http.Response, error)

	/*
	ResolveDashboardBlock Resolve a dashboard block to its computed data

	Executes the block configuration and returns computed values based on block type (stat count, gauge value, chart series, or list items)

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param dashboardId Dashboard ID
	@param blockId Block ID
	@return ApiResolveDashboardBlockRequest
	*/
	ResolveDashboardBlock(ctx context.Context, dashboardId string, blockId string) ApiResolveDashboardBlockRequest

	// ResolveDashboardBlockExecute executes the request
	//  @return ResolvedBlockResponse
	ResolveDashboardBlockExecute(r ApiResolveDashboardBlockRequest) (*ResolvedBlockResponse, *http.Response, error)

	/*
	UpdateDashboardBlock Update a dashboard block

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param dashboardId Dashboard ID
	@param blockId Block ID
	@return ApiUpdateDashboardBlockRequest
	*/
	UpdateDashboardBlock(ctx context.Context, dashboardId string, blockId string) ApiUpdateDashboardBlockRequest

	// UpdateDashboardBlockExecute executes the request
	UpdateDashboardBlockExecute(r ApiUpdateDashboardBlockRequest) (*http.Response, error)
}

// DashboardBlocksAPIService DashboardBlocksAPI service
type DashboardBlocksAPIService service

type ApiCreateDashboardBlockRequest struct {
	ctx context.Context
	ApiService DashboardBlocksAPI
	dashboardId string
	createDashboardBlockRequest *CreateDashboardBlockRequest
}

func (r ApiCreateDashboardBlockRequest) CreateDashboardBlockRequest(createDashboardBlockRequest CreateDashboardBlockRequest) ApiCreateDashboardBlockRequest {
	r.createDashboardBlockRequest = &createDashboardBlockRequest
	return r
}

func (r ApiCreateDashboardBlockRequest) Execute() (*CreateAttributeItem201Response, *http.Response, error) {
	return r.ApiService.CreateDashboardBlockExecute(r)
}

/*
CreateDashboardBlock Create a new block in a dashboard

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param dashboardId Dashboard ID
 @return ApiCreateDashboardBlockRequest
*/
func (a *DashboardBlocksAPIService) CreateDashboardBlock(ctx context.Context, dashboardId string) ApiCreateDashboardBlockRequest {
	return ApiCreateDashboardBlockRequest{
		ApiService: a,
		ctx: ctx,
		dashboardId: dashboardId,
	}
}

// Execute executes the request
//  @return CreateAttributeItem201Response
func (a *DashboardBlocksAPIService) CreateDashboardBlockExecute(r ApiCreateDashboardBlockRequest) (*CreateAttributeItem201Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CreateAttributeItem201Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DashboardBlocksAPIService.CreateDashboardBlock")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/dashboards/{dashboardId}/blocks"
	localVarPath = strings.Replace(localVarPath, "{"+"dashboardId"+"}", url.PathEscape(parameterValueToString(r.dashboardId, "dashboardId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.createDashboardBlockRequest == nil {
		return localVarReturnValue, nil, reportError("createDashboardBlockRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.createDashboardBlockRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ValidationErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiDeleteDashboardBlockRequest struct {
	ctx context.Context
	ApiService DashboardBlocksAPI
	dashboardId string
	blockId string
}

func (r ApiDeleteDashboardBlockRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeleteDashboardBlockExecute(r)
}

/*
DeleteDashboardBlock Delete a dashboard block

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param dashboardId Dashboard ID
 @param blockId Block ID
 @return ApiDeleteDashboardBlockRequest
*/
func (a *DashboardBlocksAPIService) DeleteDashboardBlock(ctx context.Context, dashboardId string, blockId string) ApiDeleteDashboardBlockRequest {
	return ApiDeleteDashboardBlockRequest{
		ApiService: a,
		ctx: ctx,
		dashboardId: dashboardId,
		blockId: blockId,
	}
}

// Execute executes the request
func (a *DashboardBlocksAPIService) DeleteDashboardBlockExecute(r ApiDeleteDashboardBlockRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DashboardBlocksAPIService.DeleteDashboardBlock")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/dashboards/{dashboardId}/blocks/{blockId}"
	localVarPath = strings.Replace(localVarPath, "{"+"dashboardId"+"}", url.PathEscape(parameterValueToString(r.dashboardId, "dashboardId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"blockId"+"}", url.PathEscape(parameterValueToString(r.blockId, "blockId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiGetDashboardBlockRequest struct {
	ctx context.Context
	ApiService DashboardBlocksAPI
	dashboardId string
	blockId string
}

func (r ApiGetDashboardBlockRequest) Execute() (*DashboardBlockResponse, *http.Response, error) {
	return r.ApiService.GetDashboardBlockExecute(r)
}

/*
GetDashboardBlock Get a dashboard block by ID

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param dashboardId Dashboard ID
 @param blockId Block ID
 @return ApiGetDashboardBlockRequest
*/
func (a *DashboardBlocksAPIService) GetDashboardBlock(ctx context.Context, dashboardId string, blockId string) ApiGetDashboardBlockRequest {
	return ApiGetDashboardBlockRequest{
		ApiService: a,
		ctx: ctx,
		dashboardId: dashboardId,
		blockId: blockId,
	}
}

// Execute executes the request
//  @return DashboardBlockResponse
func (a *DashboardBlocksAPIService) GetDashboardBlockExecute(r ApiGetDashboardBlockRequest) (*DashboardBlockResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *DashboardBlockResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DashboardBlocksAPIService.GetDashboardBlock")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/dashboards/{dashboardId}/blocks/{blockId}"
	localVarPath = strings.Replace(localVarPath, "{"+"dashboardId"+"}", url.PathEscape(parameterValueToString(r.dashboardId, "dashboardId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"blockId"+"}", url.PathEscape(parameterValueToString(r.blockId, "blockId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListDashboardBlocksRequest struct {
	ctx context.Context
	ApiService DashboardBlocksAPI
	dashboardId string
}

func (r ApiListDashboardBlocksRequest) Execute() (*ListDashboardBlocks200Response, *http.Response, error) {
	return r.ApiService.ListDashboardBlocksExecute(r)
}

/*
ListDashboardBlocks List all blocks in a dashboard

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param dashboardId Dashboard ID
 @return ApiListDashboardBlocksRequest
*/
func (a *DashboardBlocksAPIService) ListDashboardBlocks(ctx context.Context, dashboardId string) ApiListDashboardBlocksRequest {
	return ApiListDashboardBlocksRequest{
		ApiService: a,
		ctx: ctx,
		dashboardId: dashboardId,
	}
}

// Execute executes the request
//  @return ListDashboardBlocks200Response
func (a *DashboardBlocksAPIService) ListDashboardBlocksExecute(r ApiListDashboardBlocksRequest) (*ListDashboardBlocks200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ListDashboardBlocks200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DashboardBlocksAPIService.ListDashboardBlocks")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/dashboards/{dashboardId}/blocks"
	localVarPath = strings.Replace(localVarPath, "{"+"dashboardId"+"}", url.PathEscape(parameterValueToString(r.dashboardId, "dashboardId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiResolveDashboardBlockRequest struct {
	ctx context.Context
	ApiService DashboardBlocksAPI
	dashboardId string
	blockId string
}

func (r ApiResolveDashboardBlockRequest) Execute() (*ResolvedBlockResponse, *http.Response, error) {
	return r.ApiService.ResolveDashboardBlockExecute(r)
}

/*
ResolveDashboardBlock Resolve a dashboard block to its computed data

Executes the block configuration and returns computed values based on block type (stat count, gauge value, chart series, or list items)

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param dashboardId Dashboard ID
 @param blockId Block ID
 @return ApiResolveDashboardBlockRequest
*/
func (a *DashboardBlocksAPIService) ResolveDashboardBlock(ctx context.Context, dashboardId string, blockId string) ApiResolveDashboardBlockRequest {
	return ApiResolveDashboardBlockRequest{
		ApiService: a,
		ctx: ctx,
		dashboardId: dashboardId,
		blockId: blockId,
	}
}

// Execute executes the request
//  @return ResolvedBlockResponse
func (a *DashboardBlocksAPIService) ResolveDashboardBlockExecute(r ApiResolveDashboardBlockRequest) (*ResolvedBlockResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ResolvedBlockResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DashboardBlocksAPIService.ResolveDashboardBlock")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/dashboards/{dashboardId}/blocks/{blockId}/resolve"
	localVarPath = strings.Replace(localVarPath, "{"+"dashboardId"+"}", url.PathEscape(parameterValueToString(r.dashboardId, "dashboardId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"blockId"+"}", url.PathEscape(parameterValueToString(r.blockId, "blockId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUpdateDashboardBlockRequest struct {
	ctx context.Context
	ApiService DashboardBlocksAPI
	dashboardId string
	blockId string
	updateDashboardBlockRequest *UpdateDashboardBlockRequest
}

func (r ApiUpdateDashboardBlockRequest) UpdateDashboardBlockRequest(updateDashboardBlockRequest UpdateDashboardBlockRequest) ApiUpdateDashboardBlockRequest {
	r.updateDashboardBlockRequest = &updateDashboardBlockRequest
	return r
}

func (r ApiUpdateDashboardBlockRequest) Execute() (*http.Response, error) {
	return r.ApiService.UpdateDashboardBlockExecute(r)
}

/*
UpdateDashboardBlock Update a dashboard block

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param dashboardId Dashboard ID
 @param blockId Block ID
 @return ApiUpdateDashboardBlockRequest
*/
func (a *DashboardBlocksAPIService) UpdateDashboardBlock(ctx context.Context, dashboardId string, blockId string) ApiUpdateDashboardBlockRequest {
	return ApiUpdateDashboardBlockRequest{
		ApiService: a,
		ctx: ctx,
		dashboardId: dashboardId,
		blockId: blockId,
	}
}

// Execute executes the request
func (a *DashboardBlocksAPIService) UpdateDashboardBlockExecute(r ApiUpdateDashboardBlockRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DashboardBlocksAPIService.UpdateDashboardBlock")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/dashboards/{dashboardId}/blocks/{blockId}"
	localVarPath = strings.Replace(localVarPath, "{"+"dashboardId"+"}", url.PathEscape(parameterValueToString(r.dashboardId, "dashboardId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"blockId"+"}", url.PathEscape(parameterValueToString(r.blockId, "blockId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.updateDashboardBlockRequest == nil {
		return nil, reportError("updateDashboardBlockRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.updateDashboardBlockRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ValidationErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
