/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the ExecuteEntityActionResponseAction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExecuteEntityActionResponseAction{}

// ExecuteEntityActionResponseAction struct for ExecuteEntityActionResponseAction
type ExecuteEntityActionResponseAction struct {
	Id string `json:"id"`
	Slug string `json:"slug"`
	Name string `json:"name"`
	AdditionalProperties map[string]interface{}
}

type _ExecuteEntityActionResponseAction ExecuteEntityActionResponseAction

// NewExecuteEntityActionResponseAction instantiates a new ExecuteEntityActionResponseAction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExecuteEntityActionResponseAction(id string, slug string, name string) *ExecuteEntityActionResponseAction {
	this := ExecuteEntityActionResponseAction{}
	this.Id = id
	this.Slug = slug
	this.Name = name
	return &this
}

// NewExecuteEntityActionResponseActionWithDefaults instantiates a new ExecuteEntityActionResponseAction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExecuteEntityActionResponseActionWithDefaults() *ExecuteEntityActionResponseAction {
	this := ExecuteEntityActionResponseAction{}
	return &this
}

// GetId returns the Id field value
func (o *ExecuteEntityActionResponseAction) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ExecuteEntityActionResponseAction) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ExecuteEntityActionResponseAction) SetId(v string) {
	o.Id = v
}

// GetSlug returns the Slug field value
func (o *ExecuteEntityActionResponseAction) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *ExecuteEntityActionResponseAction) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *ExecuteEntityActionResponseAction) SetSlug(v string) {
	o.Slug = v
}

// GetName returns the Name field value
func (o *ExecuteEntityActionResponseAction) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ExecuteEntityActionResponseAction) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ExecuteEntityActionResponseAction) SetName(v string) {
	o.Name = v
}

func (o ExecuteEntityActionResponseAction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExecuteEntityActionResponseAction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["slug"] = o.Slug
	toSerialize["name"] = o.Name

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ExecuteEntityActionResponseAction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"slug",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExecuteEntityActionResponseAction := _ExecuteEntityActionResponseAction{}

	err = json.Unmarshal(data, &varExecuteEntityActionResponseAction)

	if err != nil {
		return err
	}

	*o = ExecuteEntityActionResponseAction(varExecuteEntityActionResponseAction)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "slug")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableExecuteEntityActionResponseAction struct {
	value *ExecuteEntityActionResponseAction
	isSet bool
}

func (v NullableExecuteEntityActionResponseAction) Get() *ExecuteEntityActionResponseAction {
	return v.value
}

func (v *NullableExecuteEntityActionResponseAction) Set(val *ExecuteEntityActionResponseAction) {
	v.value = val
	v.isSet = true
}

func (v NullableExecuteEntityActionResponseAction) IsSet() bool {
	return v.isSet
}

func (v *NullableExecuteEntityActionResponseAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExecuteEntityActionResponseAction(val *ExecuteEntityActionResponseAction) *NullableExecuteEntityActionResponseAction {
	return &NullableExecuteEntityActionResponseAction{value: val, isSet: true}
}

func (v NullableExecuteEntityActionResponseAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExecuteEntityActionResponseAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


