/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the LogAiUsageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LogAiUsageRequest{}

// LogAiUsageRequest struct for LogAiUsageRequest
type LogAiUsageRequest struct {
	// Amount of credits to deduct
	CreditsDeducted int32 `json:"credits_deducted"`
	// Model used
	Model *string `json:"model,omitempty"`
	// Input tokens
	InputTokens *int32 `json:"input_tokens,omitempty"`
	// Output tokens
	OutputTokens *int32 `json:"output_tokens,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _LogAiUsageRequest LogAiUsageRequest

// NewLogAiUsageRequest instantiates a new LogAiUsageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLogAiUsageRequest(creditsDeducted int32) *LogAiUsageRequest {
	this := LogAiUsageRequest{}
	this.CreditsDeducted = creditsDeducted
	return &this
}

// NewLogAiUsageRequestWithDefaults instantiates a new LogAiUsageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLogAiUsageRequestWithDefaults() *LogAiUsageRequest {
	this := LogAiUsageRequest{}
	return &this
}

// GetCreditsDeducted returns the CreditsDeducted field value
func (o *LogAiUsageRequest) GetCreditsDeducted() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreditsDeducted
}

// GetCreditsDeductedOk returns a tuple with the CreditsDeducted field value
// and a boolean to check if the value has been set.
func (o *LogAiUsageRequest) GetCreditsDeductedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreditsDeducted, true
}

// SetCreditsDeducted sets field value
func (o *LogAiUsageRequest) SetCreditsDeducted(v int32) {
	o.CreditsDeducted = v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *LogAiUsageRequest) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogAiUsageRequest) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *LogAiUsageRequest) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *LogAiUsageRequest) SetModel(v string) {
	o.Model = &v
}

// GetInputTokens returns the InputTokens field value if set, zero value otherwise.
func (o *LogAiUsageRequest) GetInputTokens() int32 {
	if o == nil || IsNil(o.InputTokens) {
		var ret int32
		return ret
	}
	return *o.InputTokens
}

// GetInputTokensOk returns a tuple with the InputTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogAiUsageRequest) GetInputTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.InputTokens) {
		return nil, false
	}
	return o.InputTokens, true
}

// HasInputTokens returns a boolean if a field has been set.
func (o *LogAiUsageRequest) HasInputTokens() bool {
	if o != nil && !IsNil(o.InputTokens) {
		return true
	}

	return false
}

// SetInputTokens gets a reference to the given int32 and assigns it to the InputTokens field.
func (o *LogAiUsageRequest) SetInputTokens(v int32) {
	o.InputTokens = &v
}

// GetOutputTokens returns the OutputTokens field value if set, zero value otherwise.
func (o *LogAiUsageRequest) GetOutputTokens() int32 {
	if o == nil || IsNil(o.OutputTokens) {
		var ret int32
		return ret
	}
	return *o.OutputTokens
}

// GetOutputTokensOk returns a tuple with the OutputTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogAiUsageRequest) GetOutputTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.OutputTokens) {
		return nil, false
	}
	return o.OutputTokens, true
}

// HasOutputTokens returns a boolean if a field has been set.
func (o *LogAiUsageRequest) HasOutputTokens() bool {
	if o != nil && !IsNil(o.OutputTokens) {
		return true
	}

	return false
}

// SetOutputTokens gets a reference to the given int32 and assigns it to the OutputTokens field.
func (o *LogAiUsageRequest) SetOutputTokens(v int32) {
	o.OutputTokens = &v
}

func (o LogAiUsageRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LogAiUsageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["credits_deducted"] = o.CreditsDeducted
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.InputTokens) {
		toSerialize["input_tokens"] = o.InputTokens
	}
	if !IsNil(o.OutputTokens) {
		toSerialize["output_tokens"] = o.OutputTokens
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LogAiUsageRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"credits_deducted",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLogAiUsageRequest := _LogAiUsageRequest{}

	err = json.Unmarshal(data, &varLogAiUsageRequest)

	if err != nil {
		return err
	}

	*o = LogAiUsageRequest(varLogAiUsageRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "credits_deducted")
		delete(additionalProperties, "model")
		delete(additionalProperties, "input_tokens")
		delete(additionalProperties, "output_tokens")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLogAiUsageRequest struct {
	value *LogAiUsageRequest
	isSet bool
}

func (v NullableLogAiUsageRequest) Get() *LogAiUsageRequest {
	return v.value
}

func (v *NullableLogAiUsageRequest) Set(val *LogAiUsageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLogAiUsageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLogAiUsageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogAiUsageRequest(val *LogAiUsageRequest) *NullableLogAiUsageRequest {
	return &NullableLogAiUsageRequest{value: val, isSet: true}
}

func (v NullableLogAiUsageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogAiUsageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


