/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the ActionLayoutResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActionLayoutResponse{}

// ActionLayoutResponse Visual UI presentation details for an entity action.
type ActionLayoutResponse struct {
	// Action UUID
	ActionId string `json:"action_id"`
	// Template UUID
	TemplateId string `json:"template_id"`
	// Material icon identifier for action buttons and dialogs
	Icon NullableString `json:"icon,omitempty"`
	// Display sorting rank in action menus
	SortOrder int32 `json:"sort_order"`
	AdditionalProperties map[string]interface{}
}

type _ActionLayoutResponse ActionLayoutResponse

// NewActionLayoutResponse instantiates a new ActionLayoutResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionLayoutResponse(actionId string, templateId string, sortOrder int32) *ActionLayoutResponse {
	this := ActionLayoutResponse{}
	this.ActionId = actionId
	this.TemplateId = templateId
	this.SortOrder = sortOrder
	return &this
}

// NewActionLayoutResponseWithDefaults instantiates a new ActionLayoutResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionLayoutResponseWithDefaults() *ActionLayoutResponse {
	this := ActionLayoutResponse{}
	return &this
}

// GetActionId returns the ActionId field value
func (o *ActionLayoutResponse) GetActionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ActionId
}

// GetActionIdOk returns a tuple with the ActionId field value
// and a boolean to check if the value has been set.
func (o *ActionLayoutResponse) GetActionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActionId, true
}

// SetActionId sets field value
func (o *ActionLayoutResponse) SetActionId(v string) {
	o.ActionId = v
}

// GetTemplateId returns the TemplateId field value
func (o *ActionLayoutResponse) GetTemplateId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value
// and a boolean to check if the value has been set.
func (o *ActionLayoutResponse) GetTemplateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemplateId, true
}

// SetTemplateId sets field value
func (o *ActionLayoutResponse) SetTemplateId(v string) {
	o.TemplateId = v
}

// GetIcon returns the Icon field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ActionLayoutResponse) GetIcon() string {
	if o == nil || IsNil(o.Icon.Get()) {
		var ret string
		return ret
	}
	return *o.Icon.Get()
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ActionLayoutResponse) GetIconOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Icon.Get(), o.Icon.IsSet()
}

// HasIcon returns a boolean if a field has been set.
func (o *ActionLayoutResponse) HasIcon() bool {
	if o != nil && o.Icon.IsSet() {
		return true
	}

	return false
}

// SetIcon gets a reference to the given NullableString and assigns it to the Icon field.
func (o *ActionLayoutResponse) SetIcon(v string) {
	o.Icon.Set(&v)
}
// SetIconNil sets the value for Icon to be an explicit nil
func (o *ActionLayoutResponse) SetIconNil() {
	o.Icon.Set(nil)
}

// UnsetIcon ensures that no value is present for Icon, not even an explicit nil
func (o *ActionLayoutResponse) UnsetIcon() {
	o.Icon.Unset()
}

// GetSortOrder returns the SortOrder field value
func (o *ActionLayoutResponse) GetSortOrder() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SortOrder
}

// GetSortOrderOk returns a tuple with the SortOrder field value
// and a boolean to check if the value has been set.
func (o *ActionLayoutResponse) GetSortOrderOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SortOrder, true
}

// SetSortOrder sets field value
func (o *ActionLayoutResponse) SetSortOrder(v int32) {
	o.SortOrder = v
}

func (o ActionLayoutResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActionLayoutResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action_id"] = o.ActionId
	toSerialize["template_id"] = o.TemplateId
	if o.Icon.IsSet() {
		toSerialize["icon"] = o.Icon.Get()
	}
	toSerialize["sort_order"] = o.SortOrder

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ActionLayoutResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action_id",
		"template_id",
		"sort_order",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActionLayoutResponse := _ActionLayoutResponse{}

	err = json.Unmarshal(data, &varActionLayoutResponse)

	if err != nil {
		return err
	}

	*o = ActionLayoutResponse(varActionLayoutResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "action_id")
		delete(additionalProperties, "template_id")
		delete(additionalProperties, "icon")
		delete(additionalProperties, "sort_order")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableActionLayoutResponse struct {
	value *ActionLayoutResponse
	isSet bool
}

func (v NullableActionLayoutResponse) Get() *ActionLayoutResponse {
	return v.value
}

func (v *NullableActionLayoutResponse) Set(val *ActionLayoutResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableActionLayoutResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableActionLayoutResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionLayoutResponse(val *ActionLayoutResponse) *NullableActionLayoutResponse {
	return &NullableActionLayoutResponse{value: val, isSet: true}
}

func (v NullableActionLayoutResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionLayoutResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


