/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
)

// checks if the PatchAttributeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchAttributeRequest{}

// PatchAttributeRequest Payload for partial attribute modification. All fields are optional; only provided properties will be updated.
type PatchAttributeRequest struct {
	// New human-readable name for the attribute.
	Name NullableString `json:"name,omitempty"`
	// Updated array of template UUIDs to associate. When provided, replaces the template list while safely merging restricted templates.
	TemplateIds []string `json:"template_ids,omitempty"`
	// New descriptive text for the attribute. Pass null to clear.
	Description NullableString `json:"description,omitempty"`
	ReferenceConfig NullablePatchAttributeRequestReferenceConfig `json:"reference_config,omitempty"`
	// Target data type for lossless transition on Dimension (0) attributes: Number(1)->String(0), Boolean(2)->String(0), Date(4)<->Datetime(3), Date/Datetime->String(0), String(0)<->Markdown(7).
	DataType NullableInt32 `json:"data_type,omitempty"`
	// New unique slug identifier within the project.
	Slug NullableString `json:"slug,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PatchAttributeRequest PatchAttributeRequest

// NewPatchAttributeRequest instantiates a new PatchAttributeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchAttributeRequest() *PatchAttributeRequest {
	this := PatchAttributeRequest{}
	return &this
}

// NewPatchAttributeRequestWithDefaults instantiates a new PatchAttributeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchAttributeRequestWithDefaults() *PatchAttributeRequest {
	this := PatchAttributeRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchAttributeRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchAttributeRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *PatchAttributeRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *PatchAttributeRequest) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *PatchAttributeRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *PatchAttributeRequest) UnsetName() {
	o.Name.Unset()
}

// GetTemplateIds returns the TemplateIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchAttributeRequest) GetTemplateIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.TemplateIds
}

// GetTemplateIdsOk returns a tuple with the TemplateIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchAttributeRequest) GetTemplateIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.TemplateIds) {
		return nil, false
	}
	return o.TemplateIds, true
}

// HasTemplateIds returns a boolean if a field has been set.
func (o *PatchAttributeRequest) HasTemplateIds() bool {
	if o != nil && !IsNil(o.TemplateIds) {
		return true
	}

	return false
}

// SetTemplateIds gets a reference to the given []string and assigns it to the TemplateIds field.
func (o *PatchAttributeRequest) SetTemplateIds(v []string) {
	o.TemplateIds = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchAttributeRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchAttributeRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *PatchAttributeRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *PatchAttributeRequest) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *PatchAttributeRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *PatchAttributeRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetReferenceConfig returns the ReferenceConfig field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchAttributeRequest) GetReferenceConfig() PatchAttributeRequestReferenceConfig {
	if o == nil || IsNil(o.ReferenceConfig.Get()) {
		var ret PatchAttributeRequestReferenceConfig
		return ret
	}
	return *o.ReferenceConfig.Get()
}

// GetReferenceConfigOk returns a tuple with the ReferenceConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchAttributeRequest) GetReferenceConfigOk() (*PatchAttributeRequestReferenceConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReferenceConfig.Get(), o.ReferenceConfig.IsSet()
}

// HasReferenceConfig returns a boolean if a field has been set.
func (o *PatchAttributeRequest) HasReferenceConfig() bool {
	if o != nil && o.ReferenceConfig.IsSet() {
		return true
	}

	return false
}

// SetReferenceConfig gets a reference to the given NullablePatchAttributeRequestReferenceConfig and assigns it to the ReferenceConfig field.
func (o *PatchAttributeRequest) SetReferenceConfig(v PatchAttributeRequestReferenceConfig) {
	o.ReferenceConfig.Set(&v)
}
// SetReferenceConfigNil sets the value for ReferenceConfig to be an explicit nil
func (o *PatchAttributeRequest) SetReferenceConfigNil() {
	o.ReferenceConfig.Set(nil)
}

// UnsetReferenceConfig ensures that no value is present for ReferenceConfig, not even an explicit nil
func (o *PatchAttributeRequest) UnsetReferenceConfig() {
	o.ReferenceConfig.Unset()
}

// GetDataType returns the DataType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchAttributeRequest) GetDataType() int32 {
	if o == nil || IsNil(o.DataType.Get()) {
		var ret int32
		return ret
	}
	return *o.DataType.Get()
}

// GetDataTypeOk returns a tuple with the DataType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchAttributeRequest) GetDataTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DataType.Get(), o.DataType.IsSet()
}

// HasDataType returns a boolean if a field has been set.
func (o *PatchAttributeRequest) HasDataType() bool {
	if o != nil && o.DataType.IsSet() {
		return true
	}

	return false
}

// SetDataType gets a reference to the given NullableInt32 and assigns it to the DataType field.
func (o *PatchAttributeRequest) SetDataType(v int32) {
	o.DataType.Set(&v)
}
// SetDataTypeNil sets the value for DataType to be an explicit nil
func (o *PatchAttributeRequest) SetDataTypeNil() {
	o.DataType.Set(nil)
}

// UnsetDataType ensures that no value is present for DataType, not even an explicit nil
func (o *PatchAttributeRequest) UnsetDataType() {
	o.DataType.Unset()
}

// GetSlug returns the Slug field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchAttributeRequest) GetSlug() string {
	if o == nil || IsNil(o.Slug.Get()) {
		var ret string
		return ret
	}
	return *o.Slug.Get()
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchAttributeRequest) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Slug.Get(), o.Slug.IsSet()
}

// HasSlug returns a boolean if a field has been set.
func (o *PatchAttributeRequest) HasSlug() bool {
	if o != nil && o.Slug.IsSet() {
		return true
	}

	return false
}

// SetSlug gets a reference to the given NullableString and assigns it to the Slug field.
func (o *PatchAttributeRequest) SetSlug(v string) {
	o.Slug.Set(&v)
}
// SetSlugNil sets the value for Slug to be an explicit nil
func (o *PatchAttributeRequest) SetSlugNil() {
	o.Slug.Set(nil)
}

// UnsetSlug ensures that no value is present for Slug, not even an explicit nil
func (o *PatchAttributeRequest) UnsetSlug() {
	o.Slug.Unset()
}

func (o PatchAttributeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchAttributeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.TemplateIds != nil {
		toSerialize["template_ids"] = o.TemplateIds
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.ReferenceConfig.IsSet() {
		toSerialize["reference_config"] = o.ReferenceConfig.Get()
	}
	if o.DataType.IsSet() {
		toSerialize["data_type"] = o.DataType.Get()
	}
	if o.Slug.IsSet() {
		toSerialize["slug"] = o.Slug.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatchAttributeRequest) UnmarshalJSON(data []byte) (err error) {
	varPatchAttributeRequest := _PatchAttributeRequest{}

	err = json.Unmarshal(data, &varPatchAttributeRequest)

	if err != nil {
		return err
	}

	*o = PatchAttributeRequest(varPatchAttributeRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "template_ids")
		delete(additionalProperties, "description")
		delete(additionalProperties, "reference_config")
		delete(additionalProperties, "data_type")
		delete(additionalProperties, "slug")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatchAttributeRequest struct {
	value *PatchAttributeRequest
	isSet bool
}

func (v NullablePatchAttributeRequest) Get() *PatchAttributeRequest {
	return v.value
}

func (v *NullablePatchAttributeRequest) Set(val *PatchAttributeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchAttributeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchAttributeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchAttributeRequest(val *PatchAttributeRequest) *NullablePatchAttributeRequest {
	return &NullablePatchAttributeRequest{value: val, isSet: true}
}

func (v NullablePatchAttributeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchAttributeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


