/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismith-sdk

import (
	"encoding/json"
)

// checks if the ListAttributes200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAttributes200Response{}

// ListAttributes200Response struct for ListAttributes200Response
type ListAttributes200Response struct {
	Data []AttributeResponse `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListAttributes200Response ListAttributes200Response

// NewListAttributes200Response instantiates a new ListAttributes200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAttributes200Response() *ListAttributes200Response {
	this := ListAttributes200Response{}
	return &this
}

// NewListAttributes200ResponseWithDefaults instantiates a new ListAttributes200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAttributes200ResponseWithDefaults() *ListAttributes200Response {
	this := ListAttributes200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListAttributes200Response) GetData() []AttributeResponse {
	if o == nil || IsNil(o.Data) {
		var ret []AttributeResponse
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAttributes200Response) GetDataOk() ([]AttributeResponse, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListAttributes200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []AttributeResponse and assigns it to the Data field.
func (o *ListAttributes200Response) SetData(v []AttributeResponse) {
	o.Data = v
}

func (o ListAttributes200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAttributes200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListAttributes200Response) UnmarshalJSON(data []byte) (err error) {
	varListAttributes200Response := _ListAttributes200Response{}

	err = json.Unmarshal(data, &varListAttributes200Response)

	if err != nil {
		return err
	}

	*o = ListAttributes200Response(varListAttributes200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListAttributes200Response struct {
	value *ListAttributes200Response
	isSet bool
}

func (v NullableListAttributes200Response) Get() *ListAttributes200Response {
	return v.value
}

func (v *NullableListAttributes200Response) Set(val *ListAttributes200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListAttributes200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListAttributes200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAttributes200Response(val *ListAttributes200Response) *NullableListAttributes200Response {
	return &NullableListAttributes200Response{value: val, isSet: true}
}

func (v NullableListAttributes200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAttributes200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


