/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
)

// checks if the ListTemplateViews200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListTemplateViews200Response{}

// ListTemplateViews200Response struct for ListTemplateViews200Response
type ListTemplateViews200Response struct {
	Data []WorkspaceViewResponse `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListTemplateViews200Response ListTemplateViews200Response

// NewListTemplateViews200Response instantiates a new ListTemplateViews200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListTemplateViews200Response() *ListTemplateViews200Response {
	this := ListTemplateViews200Response{}
	return &this
}

// NewListTemplateViews200ResponseWithDefaults instantiates a new ListTemplateViews200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListTemplateViews200ResponseWithDefaults() *ListTemplateViews200Response {
	this := ListTemplateViews200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListTemplateViews200Response) GetData() []WorkspaceViewResponse {
	if o == nil || IsNil(o.Data) {
		var ret []WorkspaceViewResponse
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListTemplateViews200Response) GetDataOk() ([]WorkspaceViewResponse, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListTemplateViews200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []WorkspaceViewResponse and assigns it to the Data field.
func (o *ListTemplateViews200Response) SetData(v []WorkspaceViewResponse) {
	o.Data = v
}

func (o ListTemplateViews200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListTemplateViews200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListTemplateViews200Response) UnmarshalJSON(data []byte) (err error) {
	varListTemplateViews200Response := _ListTemplateViews200Response{}

	err = json.Unmarshal(data, &varListTemplateViews200Response)

	if err != nil {
		return err
	}

	*o = ListTemplateViews200Response(varListTemplateViews200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListTemplateViews200Response struct {
	value *ListTemplateViews200Response
	isSet bool
}

func (v NullableListTemplateViews200Response) Get() *ListTemplateViews200Response {
	return v.value
}

func (v *NullableListTemplateViews200Response) Set(val *ListTemplateViews200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListTemplateViews200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListTemplateViews200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListTemplateViews200Response(val *ListTemplateViews200Response) *NullableListTemplateViews200Response {
	return &NullableListTemplateViews200Response{value: val, isSet: true}
}

func (v NullableListTemplateViews200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListTemplateViews200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


