/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the InstallMarketplaceBlueprintRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstallMarketplaceBlueprintRequest{}

// InstallMarketplaceBlueprintRequest struct for InstallMarketplaceBlueprintRequest
type InstallMarketplaceBlueprintRequest struct {
	// Target project ID
	ProjectId string `json:"project_id"`
	// Whether to install sample entities included in the blueprint
	IncludeDemoData *bool `json:"include_demo_data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InstallMarketplaceBlueprintRequest InstallMarketplaceBlueprintRequest

// NewInstallMarketplaceBlueprintRequest instantiates a new InstallMarketplaceBlueprintRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstallMarketplaceBlueprintRequest(projectId string) *InstallMarketplaceBlueprintRequest {
	this := InstallMarketplaceBlueprintRequest{}
	this.ProjectId = projectId
	var includeDemoData bool = false
	this.IncludeDemoData = &includeDemoData
	return &this
}

// NewInstallMarketplaceBlueprintRequestWithDefaults instantiates a new InstallMarketplaceBlueprintRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstallMarketplaceBlueprintRequestWithDefaults() *InstallMarketplaceBlueprintRequest {
	this := InstallMarketplaceBlueprintRequest{}
	var includeDemoData bool = false
	this.IncludeDemoData = &includeDemoData
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *InstallMarketplaceBlueprintRequest) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *InstallMarketplaceBlueprintRequest) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *InstallMarketplaceBlueprintRequest) SetProjectId(v string) {
	o.ProjectId = v
}

// GetIncludeDemoData returns the IncludeDemoData field value if set, zero value otherwise.
func (o *InstallMarketplaceBlueprintRequest) GetIncludeDemoData() bool {
	if o == nil || IsNil(o.IncludeDemoData) {
		var ret bool
		return ret
	}
	return *o.IncludeDemoData
}

// GetIncludeDemoDataOk returns a tuple with the IncludeDemoData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstallMarketplaceBlueprintRequest) GetIncludeDemoDataOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeDemoData) {
		return nil, false
	}
	return o.IncludeDemoData, true
}

// HasIncludeDemoData returns a boolean if a field has been set.
func (o *InstallMarketplaceBlueprintRequest) HasIncludeDemoData() bool {
	if o != nil && !IsNil(o.IncludeDemoData) {
		return true
	}

	return false
}

// SetIncludeDemoData gets a reference to the given bool and assigns it to the IncludeDemoData field.
func (o *InstallMarketplaceBlueprintRequest) SetIncludeDemoData(v bool) {
	o.IncludeDemoData = &v
}

func (o InstallMarketplaceBlueprintRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstallMarketplaceBlueprintRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["project_id"] = o.ProjectId
	if !IsNil(o.IncludeDemoData) {
		toSerialize["include_demo_data"] = o.IncludeDemoData
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InstallMarketplaceBlueprintRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInstallMarketplaceBlueprintRequest := _InstallMarketplaceBlueprintRequest{}

	err = json.Unmarshal(data, &varInstallMarketplaceBlueprintRequest)

	if err != nil {
		return err
	}

	*o = InstallMarketplaceBlueprintRequest(varInstallMarketplaceBlueprintRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "project_id")
		delete(additionalProperties, "include_demo_data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInstallMarketplaceBlueprintRequest struct {
	value *InstallMarketplaceBlueprintRequest
	isSet bool
}

func (v NullableInstallMarketplaceBlueprintRequest) Get() *InstallMarketplaceBlueprintRequest {
	return v.value
}

func (v *NullableInstallMarketplaceBlueprintRequest) Set(val *InstallMarketplaceBlueprintRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInstallMarketplaceBlueprintRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInstallMarketplaceBlueprintRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstallMarketplaceBlueprintRequest(val *InstallMarketplaceBlueprintRequest) *NullableInstallMarketplaceBlueprintRequest {
	return &NullableInstallMarketplaceBlueprintRequest{value: val, isSet: true}
}

func (v NullableInstallMarketplaceBlueprintRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstallMarketplaceBlueprintRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


