/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismith-sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the RegisterPushDeviceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterPushDeviceRequest{}

// RegisterPushDeviceRequest struct for RegisterPushDeviceRequest
type RegisterPushDeviceRequest struct {
	// FCM device registration token
	Token string `json:"token"`
	// Optional device name for identification
	DeviceName NullableString `json:"device_name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RegisterPushDeviceRequest RegisterPushDeviceRequest

// NewRegisterPushDeviceRequest instantiates a new RegisterPushDeviceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterPushDeviceRequest(token string) *RegisterPushDeviceRequest {
	this := RegisterPushDeviceRequest{}
	this.Token = token
	return &this
}

// NewRegisterPushDeviceRequestWithDefaults instantiates a new RegisterPushDeviceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterPushDeviceRequestWithDefaults() *RegisterPushDeviceRequest {
	this := RegisterPushDeviceRequest{}
	return &this
}

// GetToken returns the Token field value
func (o *RegisterPushDeviceRequest) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *RegisterPushDeviceRequest) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *RegisterPushDeviceRequest) SetToken(v string) {
	o.Token = v
}

// GetDeviceName returns the DeviceName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RegisterPushDeviceRequest) GetDeviceName() string {
	if o == nil || IsNil(o.DeviceName.Get()) {
		var ret string
		return ret
	}
	return *o.DeviceName.Get()
}

// GetDeviceNameOk returns a tuple with the DeviceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RegisterPushDeviceRequest) GetDeviceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeviceName.Get(), o.DeviceName.IsSet()
}

// HasDeviceName returns a boolean if a field has been set.
func (o *RegisterPushDeviceRequest) HasDeviceName() bool {
	if o != nil && o.DeviceName.IsSet() {
		return true
	}

	return false
}

// SetDeviceName gets a reference to the given NullableString and assigns it to the DeviceName field.
func (o *RegisterPushDeviceRequest) SetDeviceName(v string) {
	o.DeviceName.Set(&v)
}
// SetDeviceNameNil sets the value for DeviceName to be an explicit nil
func (o *RegisterPushDeviceRequest) SetDeviceNameNil() {
	o.DeviceName.Set(nil)
}

// UnsetDeviceName ensures that no value is present for DeviceName, not even an explicit nil
func (o *RegisterPushDeviceRequest) UnsetDeviceName() {
	o.DeviceName.Unset()
}

func (o RegisterPushDeviceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterPushDeviceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token"] = o.Token
	if o.DeviceName.IsSet() {
		toSerialize["device_name"] = o.DeviceName.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RegisterPushDeviceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterPushDeviceRequest := _RegisterPushDeviceRequest{}

	err = json.Unmarshal(data, &varRegisterPushDeviceRequest)

	if err != nil {
		return err
	}

	*o = RegisterPushDeviceRequest(varRegisterPushDeviceRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "token")
		delete(additionalProperties, "device_name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRegisterPushDeviceRequest struct {
	value *RegisterPushDeviceRequest
	isSet bool
}

func (v NullableRegisterPushDeviceRequest) Get() *RegisterPushDeviceRequest {
	return v.value
}

func (v *NullableRegisterPushDeviceRequest) Set(val *RegisterPushDeviceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterPushDeviceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterPushDeviceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterPushDeviceRequest(val *RegisterPushDeviceRequest) *NullableRegisterPushDeviceRequest {
	return &NullableRegisterPushDeviceRequest{value: val, isSet: true}
}

func (v NullableRegisterPushDeviceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterPushDeviceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


