/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
)

// checks if the SearchEntitiesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchEntitiesRequest{}

// SearchEntitiesRequest Filter and global search criteria for querying template entities
type SearchEntitiesRequest struct {
	// Full-text and substring query string, matched across all string and text dimension attributes of the template
	GlobalSearch NullableString `json:"global_search,omitempty"`
	// Filter groups: clauses inside a group are AND-ed, groups are OR-ed. `[]` applies no filter, `[[a, b]]` is `a AND b`, `[[a], [b, c]]` is `a OR (b AND c)`. Each clause is `{field, operator, value}` — see the `EntityFilter` schema for the shape. Unknown fields, operators that do not fit the field, malformed values, and reference paths into a template you cannot view are refused with 400/403.
	FilterGroups [][]EntityFilter `json:"filter_groups,omitempty"`
	// When true, each record's attribute_values is an array of EntityAttributeValue items (attribute id, slug, raw value, resolved custom_value, reference_entity_id). When false (default), attribute_values is a compact object mapping attribute slug to display value, with the ids behind list, reference and file labels in list_item_ids, reference_entity_ids and file_ids.
	Verbose *bool `json:"verbose,omitempty"`
	// Optional list of attribute slugs or UUIDs to project, e.g. [\"title\", \"status\"]. Standard fields (id, template_id, template_slug, created_at, updated_at, external_key) are always included and do not need to be listed. When specified, database queries only hydrate the requested attributes, drastically reducing response payload size and execution latency. If omitted, all attributes defined on the template are returned.
	Fields []string `json:"fields,omitempty"`
	GroupKey *SearchEntitiesRequestGroupKey `json:"group_key,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SearchEntitiesRequest SearchEntitiesRequest

// NewSearchEntitiesRequest instantiates a new SearchEntitiesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchEntitiesRequest() *SearchEntitiesRequest {
	this := SearchEntitiesRequest{}
	var verbose bool = false
	this.Verbose = &verbose
	return &this
}

// NewSearchEntitiesRequestWithDefaults instantiates a new SearchEntitiesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchEntitiesRequestWithDefaults() *SearchEntitiesRequest {
	this := SearchEntitiesRequest{}
	var verbose bool = false
	this.Verbose = &verbose
	return &this
}

// GetGlobalSearch returns the GlobalSearch field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchEntitiesRequest) GetGlobalSearch() string {
	if o == nil || IsNil(o.GlobalSearch.Get()) {
		var ret string
		return ret
	}
	return *o.GlobalSearch.Get()
}

// GetGlobalSearchOk returns a tuple with the GlobalSearch field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchEntitiesRequest) GetGlobalSearchOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GlobalSearch.Get(), o.GlobalSearch.IsSet()
}

// HasGlobalSearch returns a boolean if a field has been set.
func (o *SearchEntitiesRequest) HasGlobalSearch() bool {
	if o != nil && o.GlobalSearch.IsSet() {
		return true
	}

	return false
}

// SetGlobalSearch gets a reference to the given NullableString and assigns it to the GlobalSearch field.
func (o *SearchEntitiesRequest) SetGlobalSearch(v string) {
	o.GlobalSearch.Set(&v)
}
// SetGlobalSearchNil sets the value for GlobalSearch to be an explicit nil
func (o *SearchEntitiesRequest) SetGlobalSearchNil() {
	o.GlobalSearch.Set(nil)
}

// UnsetGlobalSearch ensures that no value is present for GlobalSearch, not even an explicit nil
func (o *SearchEntitiesRequest) UnsetGlobalSearch() {
	o.GlobalSearch.Unset()
}

// GetFilterGroups returns the FilterGroups field value if set, zero value otherwise.
func (o *SearchEntitiesRequest) GetFilterGroups() [][]EntityFilter {
	if o == nil || IsNil(o.FilterGroups) {
		var ret [][]EntityFilter
		return ret
	}
	return o.FilterGroups
}

// GetFilterGroupsOk returns a tuple with the FilterGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchEntitiesRequest) GetFilterGroupsOk() ([][]EntityFilter, bool) {
	if o == nil || IsNil(o.FilterGroups) {
		return nil, false
	}
	return o.FilterGroups, true
}

// HasFilterGroups returns a boolean if a field has been set.
func (o *SearchEntitiesRequest) HasFilterGroups() bool {
	if o != nil && !IsNil(o.FilterGroups) {
		return true
	}

	return false
}

// SetFilterGroups gets a reference to the given [][]EntityFilter and assigns it to the FilterGroups field.
func (o *SearchEntitiesRequest) SetFilterGroups(v [][]EntityFilter) {
	o.FilterGroups = v
}

// GetVerbose returns the Verbose field value if set, zero value otherwise.
func (o *SearchEntitiesRequest) GetVerbose() bool {
	if o == nil || IsNil(o.Verbose) {
		var ret bool
		return ret
	}
	return *o.Verbose
}

// GetVerboseOk returns a tuple with the Verbose field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchEntitiesRequest) GetVerboseOk() (*bool, bool) {
	if o == nil || IsNil(o.Verbose) {
		return nil, false
	}
	return o.Verbose, true
}

// HasVerbose returns a boolean if a field has been set.
func (o *SearchEntitiesRequest) HasVerbose() bool {
	if o != nil && !IsNil(o.Verbose) {
		return true
	}

	return false
}

// SetVerbose gets a reference to the given bool and assigns it to the Verbose field.
func (o *SearchEntitiesRequest) SetVerbose(v bool) {
	o.Verbose = &v
}

// GetFields returns the Fields field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchEntitiesRequest) GetFields() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchEntitiesRequest) GetFieldsOk() ([]string, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *SearchEntitiesRequest) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given []string and assigns it to the Fields field.
func (o *SearchEntitiesRequest) SetFields(v []string) {
	o.Fields = v
}

// GetGroupKey returns the GroupKey field value if set, zero value otherwise.
func (o *SearchEntitiesRequest) GetGroupKey() SearchEntitiesRequestGroupKey {
	if o == nil || IsNil(o.GroupKey) {
		var ret SearchEntitiesRequestGroupKey
		return ret
	}
	return *o.GroupKey
}

// GetGroupKeyOk returns a tuple with the GroupKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchEntitiesRequest) GetGroupKeyOk() (*SearchEntitiesRequestGroupKey, bool) {
	if o == nil || IsNil(o.GroupKey) {
		return nil, false
	}
	return o.GroupKey, true
}

// HasGroupKey returns a boolean if a field has been set.
func (o *SearchEntitiesRequest) HasGroupKey() bool {
	if o != nil && !IsNil(o.GroupKey) {
		return true
	}

	return false
}

// SetGroupKey gets a reference to the given SearchEntitiesRequestGroupKey and assigns it to the GroupKey field.
func (o *SearchEntitiesRequest) SetGroupKey(v SearchEntitiesRequestGroupKey) {
	o.GroupKey = &v
}

func (o SearchEntitiesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchEntitiesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.GlobalSearch.IsSet() {
		toSerialize["global_search"] = o.GlobalSearch.Get()
	}
	if !IsNil(o.FilterGroups) {
		toSerialize["filter_groups"] = o.FilterGroups
	}
	if !IsNil(o.Verbose) {
		toSerialize["verbose"] = o.Verbose
	}
	if o.Fields != nil {
		toSerialize["fields"] = o.Fields
	}
	if !IsNil(o.GroupKey) {
		toSerialize["group_key"] = o.GroupKey
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SearchEntitiesRequest) UnmarshalJSON(data []byte) (err error) {
	varSearchEntitiesRequest := _SearchEntitiesRequest{}

	err = json.Unmarshal(data, &varSearchEntitiesRequest)

	if err != nil {
		return err
	}

	*o = SearchEntitiesRequest(varSearchEntitiesRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "global_search")
		delete(additionalProperties, "filter_groups")
		delete(additionalProperties, "verbose")
		delete(additionalProperties, "fields")
		delete(additionalProperties, "group_key")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSearchEntitiesRequest struct {
	value *SearchEntitiesRequest
	isSet bool
}

func (v NullableSearchEntitiesRequest) Get() *SearchEntitiesRequest {
	return v.value
}

func (v *NullableSearchEntitiesRequest) Set(val *SearchEntitiesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchEntitiesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchEntitiesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchEntitiesRequest(val *SearchEntitiesRequest) *NullableSearchEntitiesRequest {
	return &NullableSearchEntitiesRequest{value: val, isSet: true}
}

func (v NullableSearchEntitiesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchEntitiesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


