/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.11
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
)

// checks if the MarketplaceBlueprintDetailResponseMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MarketplaceBlueprintDetailResponseMetadata{}

// MarketplaceBlueprintDetailResponseMetadata Blueprint metadata including keywords and install stats
type MarketplaceBlueprintDetailResponseMetadata struct {
	// Categorization keywords
	Keywords []string `json:"keywords,omitempty"`
	// Total number of installations across all projects
	Installs *int32 `json:"installs,omitempty"`
	// Schema version of the blueprint package
	Version *int32 `json:"version,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MarketplaceBlueprintDetailResponseMetadata MarketplaceBlueprintDetailResponseMetadata

// NewMarketplaceBlueprintDetailResponseMetadata instantiates a new MarketplaceBlueprintDetailResponseMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMarketplaceBlueprintDetailResponseMetadata() *MarketplaceBlueprintDetailResponseMetadata {
	this := MarketplaceBlueprintDetailResponseMetadata{}
	return &this
}

// NewMarketplaceBlueprintDetailResponseMetadataWithDefaults instantiates a new MarketplaceBlueprintDetailResponseMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMarketplaceBlueprintDetailResponseMetadataWithDefaults() *MarketplaceBlueprintDetailResponseMetadata {
	this := MarketplaceBlueprintDetailResponseMetadata{}
	return &this
}

// GetKeywords returns the Keywords field value if set, zero value otherwise.
func (o *MarketplaceBlueprintDetailResponseMetadata) GetKeywords() []string {
	if o == nil || IsNil(o.Keywords) {
		var ret []string
		return ret
	}
	return o.Keywords
}

// GetKeywordsOk returns a tuple with the Keywords field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketplaceBlueprintDetailResponseMetadata) GetKeywordsOk() ([]string, bool) {
	if o == nil || IsNil(o.Keywords) {
		return nil, false
	}
	return o.Keywords, true
}

// HasKeywords returns a boolean if a field has been set.
func (o *MarketplaceBlueprintDetailResponseMetadata) HasKeywords() bool {
	if o != nil && !IsNil(o.Keywords) {
		return true
	}

	return false
}

// SetKeywords gets a reference to the given []string and assigns it to the Keywords field.
func (o *MarketplaceBlueprintDetailResponseMetadata) SetKeywords(v []string) {
	o.Keywords = v
}

// GetInstalls returns the Installs field value if set, zero value otherwise.
func (o *MarketplaceBlueprintDetailResponseMetadata) GetInstalls() int32 {
	if o == nil || IsNil(o.Installs) {
		var ret int32
		return ret
	}
	return *o.Installs
}

// GetInstallsOk returns a tuple with the Installs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketplaceBlueprintDetailResponseMetadata) GetInstallsOk() (*int32, bool) {
	if o == nil || IsNil(o.Installs) {
		return nil, false
	}
	return o.Installs, true
}

// HasInstalls returns a boolean if a field has been set.
func (o *MarketplaceBlueprintDetailResponseMetadata) HasInstalls() bool {
	if o != nil && !IsNil(o.Installs) {
		return true
	}

	return false
}

// SetInstalls gets a reference to the given int32 and assigns it to the Installs field.
func (o *MarketplaceBlueprintDetailResponseMetadata) SetInstalls(v int32) {
	o.Installs = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *MarketplaceBlueprintDetailResponseMetadata) GetVersion() int32 {
	if o == nil || IsNil(o.Version) {
		var ret int32
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketplaceBlueprintDetailResponseMetadata) GetVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *MarketplaceBlueprintDetailResponseMetadata) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int32 and assigns it to the Version field.
func (o *MarketplaceBlueprintDetailResponseMetadata) SetVersion(v int32) {
	o.Version = &v
}

func (o MarketplaceBlueprintDetailResponseMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MarketplaceBlueprintDetailResponseMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Keywords) {
		toSerialize["keywords"] = o.Keywords
	}
	if !IsNil(o.Installs) {
		toSerialize["installs"] = o.Installs
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MarketplaceBlueprintDetailResponseMetadata) UnmarshalJSON(data []byte) (err error) {
	varMarketplaceBlueprintDetailResponseMetadata := _MarketplaceBlueprintDetailResponseMetadata{}

	err = json.Unmarshal(data, &varMarketplaceBlueprintDetailResponseMetadata)

	if err != nil {
		return err
	}

	*o = MarketplaceBlueprintDetailResponseMetadata(varMarketplaceBlueprintDetailResponseMetadata)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "keywords")
		delete(additionalProperties, "installs")
		delete(additionalProperties, "version")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMarketplaceBlueprintDetailResponseMetadata struct {
	value *MarketplaceBlueprintDetailResponseMetadata
	isSet bool
}

func (v NullableMarketplaceBlueprintDetailResponseMetadata) Get() *MarketplaceBlueprintDetailResponseMetadata {
	return v.value
}

func (v *NullableMarketplaceBlueprintDetailResponseMetadata) Set(val *MarketplaceBlueprintDetailResponseMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableMarketplaceBlueprintDetailResponseMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableMarketplaceBlueprintDetailResponseMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMarketplaceBlueprintDetailResponseMetadata(val *MarketplaceBlueprintDetailResponseMetadata) *NullableMarketplaceBlueprintDetailResponseMetadata {
	return &NullableMarketplaceBlueprintDetailResponseMetadata{value: val, isSet: true}
}

func (v NullableMarketplaceBlueprintDetailResponseMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMarketplaceBlueprintDetailResponseMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


