/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismith-sdk

import (
	"encoding/json"
)

// checks if the PortalUrlResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PortalUrlResponse{}

// PortalUrlResponse Customer portal URL for subscription management
type PortalUrlResponse struct {
	// URL to redirect user to manage their subscription
	PortalUrl *string `json:"portal_url,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PortalUrlResponse PortalUrlResponse

// NewPortalUrlResponse instantiates a new PortalUrlResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPortalUrlResponse() *PortalUrlResponse {
	this := PortalUrlResponse{}
	return &this
}

// NewPortalUrlResponseWithDefaults instantiates a new PortalUrlResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPortalUrlResponseWithDefaults() *PortalUrlResponse {
	this := PortalUrlResponse{}
	return &this
}

// GetPortalUrl returns the PortalUrl field value if set, zero value otherwise.
func (o *PortalUrlResponse) GetPortalUrl() string {
	if o == nil || IsNil(o.PortalUrl) {
		var ret string
		return ret
	}
	return *o.PortalUrl
}

// GetPortalUrlOk returns a tuple with the PortalUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortalUrlResponse) GetPortalUrlOk() (*string, bool) {
	if o == nil || IsNil(o.PortalUrl) {
		return nil, false
	}
	return o.PortalUrl, true
}

// HasPortalUrl returns a boolean if a field has been set.
func (o *PortalUrlResponse) HasPortalUrl() bool {
	if o != nil && !IsNil(o.PortalUrl) {
		return true
	}

	return false
}

// SetPortalUrl gets a reference to the given string and assigns it to the PortalUrl field.
func (o *PortalUrlResponse) SetPortalUrl(v string) {
	o.PortalUrl = &v
}

func (o PortalUrlResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PortalUrlResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PortalUrl) {
		toSerialize["portal_url"] = o.PortalUrl
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PortalUrlResponse) UnmarshalJSON(data []byte) (err error) {
	varPortalUrlResponse := _PortalUrlResponse{}

	err = json.Unmarshal(data, &varPortalUrlResponse)

	if err != nil {
		return err
	}

	*o = PortalUrlResponse(varPortalUrlResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "portal_url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePortalUrlResponse struct {
	value *PortalUrlResponse
	isSet bool
}

func (v NullablePortalUrlResponse) Get() *PortalUrlResponse {
	return v.value
}

func (v *NullablePortalUrlResponse) Set(val *PortalUrlResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePortalUrlResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePortalUrlResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePortalUrlResponse(val *PortalUrlResponse) *NullablePortalUrlResponse {
	return &NullablePortalUrlResponse{value: val, isSet: true}
}

func (v NullablePortalUrlResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePortalUrlResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


