/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.11
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateWorkspaceViewRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateWorkspaceViewRequest{}

// CreateWorkspaceViewRequest Payload for adding a new view / pane to a workspace
type CreateWorkspaceViewRequest struct {
	// Target template ID defining entity schema bound to this view pane
	TemplateId string `json:"template_id"`
	// Display label for the view pane tab or header
	Name string `json:"name"`
	// Dynamic filtering rules applied to entities rendered in this view pane
	Filters []map[string]interface{} `json:"filters,omitempty"`
	// Initial search query string applied to entities in this view
	SearchString NullableString `json:"search_string,omitempty"`
	// Search execution mode (keyword text search or semantic vector similarity search)
	SearchMode *string `json:"search_mode,omitempty"`
	Sort NullableCreateWorkspaceViewRequestSort `json:"sort,omitempty"`
	// Presentation layout type for entity records (table or card grid)
	DisplayMode *string `json:"display_mode,omitempty"`
	// List of attribute slugs or UUIDs to display as columns in table mode
	DisplayedColumns []string `json:"displayed_columns,omitempty"`
	// Display sequence index of this pane within the workspace layout
	PaneOrder NullableInt32 `json:"pane_order,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateWorkspaceViewRequest CreateWorkspaceViewRequest

// NewCreateWorkspaceViewRequest instantiates a new CreateWorkspaceViewRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateWorkspaceViewRequest(templateId string, name string) *CreateWorkspaceViewRequest {
	this := CreateWorkspaceViewRequest{}
	this.TemplateId = templateId
	this.Name = name
	var searchMode string = "keyword"
	this.SearchMode = &searchMode
	var displayMode string = "table"
	this.DisplayMode = &displayMode
	return &this
}

// NewCreateWorkspaceViewRequestWithDefaults instantiates a new CreateWorkspaceViewRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateWorkspaceViewRequestWithDefaults() *CreateWorkspaceViewRequest {
	this := CreateWorkspaceViewRequest{}
	var searchMode string = "keyword"
	this.SearchMode = &searchMode
	var displayMode string = "table"
	this.DisplayMode = &displayMode
	return &this
}

// GetTemplateId returns the TemplateId field value
func (o *CreateWorkspaceViewRequest) GetTemplateId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value
// and a boolean to check if the value has been set.
func (o *CreateWorkspaceViewRequest) GetTemplateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemplateId, true
}

// SetTemplateId sets field value
func (o *CreateWorkspaceViewRequest) SetTemplateId(v string) {
	o.TemplateId = v
}

// GetName returns the Name field value
func (o *CreateWorkspaceViewRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateWorkspaceViewRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateWorkspaceViewRequest) SetName(v string) {
	o.Name = v
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *CreateWorkspaceViewRequest) GetFilters() []map[string]interface{} {
	if o == nil || IsNil(o.Filters) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWorkspaceViewRequest) GetFiltersOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Filters) {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *CreateWorkspaceViewRequest) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given []map[string]interface{} and assigns it to the Filters field.
func (o *CreateWorkspaceViewRequest) SetFilters(v []map[string]interface{}) {
	o.Filters = v
}

// GetSearchString returns the SearchString field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateWorkspaceViewRequest) GetSearchString() string {
	if o == nil || IsNil(o.SearchString.Get()) {
		var ret string
		return ret
	}
	return *o.SearchString.Get()
}

// GetSearchStringOk returns a tuple with the SearchString field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateWorkspaceViewRequest) GetSearchStringOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SearchString.Get(), o.SearchString.IsSet()
}

// HasSearchString returns a boolean if a field has been set.
func (o *CreateWorkspaceViewRequest) HasSearchString() bool {
	if o != nil && o.SearchString.IsSet() {
		return true
	}

	return false
}

// SetSearchString gets a reference to the given NullableString and assigns it to the SearchString field.
func (o *CreateWorkspaceViewRequest) SetSearchString(v string) {
	o.SearchString.Set(&v)
}
// SetSearchStringNil sets the value for SearchString to be an explicit nil
func (o *CreateWorkspaceViewRequest) SetSearchStringNil() {
	o.SearchString.Set(nil)
}

// UnsetSearchString ensures that no value is present for SearchString, not even an explicit nil
func (o *CreateWorkspaceViewRequest) UnsetSearchString() {
	o.SearchString.Unset()
}

// GetSearchMode returns the SearchMode field value if set, zero value otherwise.
func (o *CreateWorkspaceViewRequest) GetSearchMode() string {
	if o == nil || IsNil(o.SearchMode) {
		var ret string
		return ret
	}
	return *o.SearchMode
}

// GetSearchModeOk returns a tuple with the SearchMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWorkspaceViewRequest) GetSearchModeOk() (*string, bool) {
	if o == nil || IsNil(o.SearchMode) {
		return nil, false
	}
	return o.SearchMode, true
}

// HasSearchMode returns a boolean if a field has been set.
func (o *CreateWorkspaceViewRequest) HasSearchMode() bool {
	if o != nil && !IsNil(o.SearchMode) {
		return true
	}

	return false
}

// SetSearchMode gets a reference to the given string and assigns it to the SearchMode field.
func (o *CreateWorkspaceViewRequest) SetSearchMode(v string) {
	o.SearchMode = &v
}

// GetSort returns the Sort field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateWorkspaceViewRequest) GetSort() CreateWorkspaceViewRequestSort {
	if o == nil || IsNil(o.Sort.Get()) {
		var ret CreateWorkspaceViewRequestSort
		return ret
	}
	return *o.Sort.Get()
}

// GetSortOk returns a tuple with the Sort field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateWorkspaceViewRequest) GetSortOk() (*CreateWorkspaceViewRequestSort, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sort.Get(), o.Sort.IsSet()
}

// HasSort returns a boolean if a field has been set.
func (o *CreateWorkspaceViewRequest) HasSort() bool {
	if o != nil && o.Sort.IsSet() {
		return true
	}

	return false
}

// SetSort gets a reference to the given NullableCreateWorkspaceViewRequestSort and assigns it to the Sort field.
func (o *CreateWorkspaceViewRequest) SetSort(v CreateWorkspaceViewRequestSort) {
	o.Sort.Set(&v)
}
// SetSortNil sets the value for Sort to be an explicit nil
func (o *CreateWorkspaceViewRequest) SetSortNil() {
	o.Sort.Set(nil)
}

// UnsetSort ensures that no value is present for Sort, not even an explicit nil
func (o *CreateWorkspaceViewRequest) UnsetSort() {
	o.Sort.Unset()
}

// GetDisplayMode returns the DisplayMode field value if set, zero value otherwise.
func (o *CreateWorkspaceViewRequest) GetDisplayMode() string {
	if o == nil || IsNil(o.DisplayMode) {
		var ret string
		return ret
	}
	return *o.DisplayMode
}

// GetDisplayModeOk returns a tuple with the DisplayMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWorkspaceViewRequest) GetDisplayModeOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayMode) {
		return nil, false
	}
	return o.DisplayMode, true
}

// HasDisplayMode returns a boolean if a field has been set.
func (o *CreateWorkspaceViewRequest) HasDisplayMode() bool {
	if o != nil && !IsNil(o.DisplayMode) {
		return true
	}

	return false
}

// SetDisplayMode gets a reference to the given string and assigns it to the DisplayMode field.
func (o *CreateWorkspaceViewRequest) SetDisplayMode(v string) {
	o.DisplayMode = &v
}

// GetDisplayedColumns returns the DisplayedColumns field value if set, zero value otherwise.
func (o *CreateWorkspaceViewRequest) GetDisplayedColumns() []string {
	if o == nil || IsNil(o.DisplayedColumns) {
		var ret []string
		return ret
	}
	return o.DisplayedColumns
}

// GetDisplayedColumnsOk returns a tuple with the DisplayedColumns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWorkspaceViewRequest) GetDisplayedColumnsOk() ([]string, bool) {
	if o == nil || IsNil(o.DisplayedColumns) {
		return nil, false
	}
	return o.DisplayedColumns, true
}

// HasDisplayedColumns returns a boolean if a field has been set.
func (o *CreateWorkspaceViewRequest) HasDisplayedColumns() bool {
	if o != nil && !IsNil(o.DisplayedColumns) {
		return true
	}

	return false
}

// SetDisplayedColumns gets a reference to the given []string and assigns it to the DisplayedColumns field.
func (o *CreateWorkspaceViewRequest) SetDisplayedColumns(v []string) {
	o.DisplayedColumns = v
}

// GetPaneOrder returns the PaneOrder field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateWorkspaceViewRequest) GetPaneOrder() int32 {
	if o == nil || IsNil(o.PaneOrder.Get()) {
		var ret int32
		return ret
	}
	return *o.PaneOrder.Get()
}

// GetPaneOrderOk returns a tuple with the PaneOrder field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateWorkspaceViewRequest) GetPaneOrderOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PaneOrder.Get(), o.PaneOrder.IsSet()
}

// HasPaneOrder returns a boolean if a field has been set.
func (o *CreateWorkspaceViewRequest) HasPaneOrder() bool {
	if o != nil && o.PaneOrder.IsSet() {
		return true
	}

	return false
}

// SetPaneOrder gets a reference to the given NullableInt32 and assigns it to the PaneOrder field.
func (o *CreateWorkspaceViewRequest) SetPaneOrder(v int32) {
	o.PaneOrder.Set(&v)
}
// SetPaneOrderNil sets the value for PaneOrder to be an explicit nil
func (o *CreateWorkspaceViewRequest) SetPaneOrderNil() {
	o.PaneOrder.Set(nil)
}

// UnsetPaneOrder ensures that no value is present for PaneOrder, not even an explicit nil
func (o *CreateWorkspaceViewRequest) UnsetPaneOrder() {
	o.PaneOrder.Unset()
}

func (o CreateWorkspaceViewRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateWorkspaceViewRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["template_id"] = o.TemplateId
	toSerialize["name"] = o.Name
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	if o.SearchString.IsSet() {
		toSerialize["search_string"] = o.SearchString.Get()
	}
	if !IsNil(o.SearchMode) {
		toSerialize["search_mode"] = o.SearchMode
	}
	if o.Sort.IsSet() {
		toSerialize["sort"] = o.Sort.Get()
	}
	if !IsNil(o.DisplayMode) {
		toSerialize["display_mode"] = o.DisplayMode
	}
	if !IsNil(o.DisplayedColumns) {
		toSerialize["displayed_columns"] = o.DisplayedColumns
	}
	if o.PaneOrder.IsSet() {
		toSerialize["pane_order"] = o.PaneOrder.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateWorkspaceViewRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"template_id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateWorkspaceViewRequest := _CreateWorkspaceViewRequest{}

	err = json.Unmarshal(data, &varCreateWorkspaceViewRequest)

	if err != nil {
		return err
	}

	*o = CreateWorkspaceViewRequest(varCreateWorkspaceViewRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "template_id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "filters")
		delete(additionalProperties, "search_string")
		delete(additionalProperties, "search_mode")
		delete(additionalProperties, "sort")
		delete(additionalProperties, "display_mode")
		delete(additionalProperties, "displayed_columns")
		delete(additionalProperties, "pane_order")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateWorkspaceViewRequest struct {
	value *CreateWorkspaceViewRequest
	isSet bool
}

func (v NullableCreateWorkspaceViewRequest) Get() *CreateWorkspaceViewRequest {
	return v.value
}

func (v *NullableCreateWorkspaceViewRequest) Set(val *CreateWorkspaceViewRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateWorkspaceViewRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateWorkspaceViewRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateWorkspaceViewRequest(val *CreateWorkspaceViewRequest) *NullableCreateWorkspaceViewRequest {
	return &NullableCreateWorkspaceViewRequest{value: val, isSet: true}
}

func (v NullableCreateWorkspaceViewRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateWorkspaceViewRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


