/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
)

// checks if the PreviewInboundMappingRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PreviewInboundMappingRequest{}

// PreviewInboundMappingRequest Send exactly one of `body` and `delivery_id`.
type PreviewInboundMappingRequest struct {
	// A sample payload, as the sender would post it: for example the sample event in the sender's webhook documentation.
	Body map[string]interface{} `json:"body,omitempty"`
	// A delivery from the endpoint's log to use as the sample instead: the `log_id` the sender was answered with.
	DeliveryId *string `json:"delivery_id,omitempty"`
	// A mapping to try instead of the saved one, in the same shape as the endpoint's `mapping`. It is not saved.
	Mapping map[string]interface{} `json:"mapping,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PreviewInboundMappingRequest PreviewInboundMappingRequest

// NewPreviewInboundMappingRequest instantiates a new PreviewInboundMappingRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPreviewInboundMappingRequest() *PreviewInboundMappingRequest {
	this := PreviewInboundMappingRequest{}
	return &this
}

// NewPreviewInboundMappingRequestWithDefaults instantiates a new PreviewInboundMappingRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPreviewInboundMappingRequestWithDefaults() *PreviewInboundMappingRequest {
	this := PreviewInboundMappingRequest{}
	return &this
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *PreviewInboundMappingRequest) GetBody() map[string]interface{} {
	if o == nil || IsNil(o.Body) {
		var ret map[string]interface{}
		return ret
	}
	return o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreviewInboundMappingRequest) GetBodyOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Body) {
		return map[string]interface{}{}, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *PreviewInboundMappingRequest) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given map[string]interface{} and assigns it to the Body field.
func (o *PreviewInboundMappingRequest) SetBody(v map[string]interface{}) {
	o.Body = v
}

// GetDeliveryId returns the DeliveryId field value if set, zero value otherwise.
func (o *PreviewInboundMappingRequest) GetDeliveryId() string {
	if o == nil || IsNil(o.DeliveryId) {
		var ret string
		return ret
	}
	return *o.DeliveryId
}

// GetDeliveryIdOk returns a tuple with the DeliveryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreviewInboundMappingRequest) GetDeliveryIdOk() (*string, bool) {
	if o == nil || IsNil(o.DeliveryId) {
		return nil, false
	}
	return o.DeliveryId, true
}

// HasDeliveryId returns a boolean if a field has been set.
func (o *PreviewInboundMappingRequest) HasDeliveryId() bool {
	if o != nil && !IsNil(o.DeliveryId) {
		return true
	}

	return false
}

// SetDeliveryId gets a reference to the given string and assigns it to the DeliveryId field.
func (o *PreviewInboundMappingRequest) SetDeliveryId(v string) {
	o.DeliveryId = &v
}

// GetMapping returns the Mapping field value if set, zero value otherwise.
func (o *PreviewInboundMappingRequest) GetMapping() map[string]interface{} {
	if o == nil || IsNil(o.Mapping) {
		var ret map[string]interface{}
		return ret
	}
	return o.Mapping
}

// GetMappingOk returns a tuple with the Mapping field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreviewInboundMappingRequest) GetMappingOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Mapping) {
		return map[string]interface{}{}, false
	}
	return o.Mapping, true
}

// HasMapping returns a boolean if a field has been set.
func (o *PreviewInboundMappingRequest) HasMapping() bool {
	if o != nil && !IsNil(o.Mapping) {
		return true
	}

	return false
}

// SetMapping gets a reference to the given map[string]interface{} and assigns it to the Mapping field.
func (o *PreviewInboundMappingRequest) SetMapping(v map[string]interface{}) {
	o.Mapping = v
}

func (o PreviewInboundMappingRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PreviewInboundMappingRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.DeliveryId) {
		toSerialize["delivery_id"] = o.DeliveryId
	}
	if !IsNil(o.Mapping) {
		toSerialize["mapping"] = o.Mapping
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PreviewInboundMappingRequest) UnmarshalJSON(data []byte) (err error) {
	varPreviewInboundMappingRequest := _PreviewInboundMappingRequest{}

	err = json.Unmarshal(data, &varPreviewInboundMappingRequest)

	if err != nil {
		return err
	}

	*o = PreviewInboundMappingRequest(varPreviewInboundMappingRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "body")
		delete(additionalProperties, "delivery_id")
		delete(additionalProperties, "mapping")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePreviewInboundMappingRequest struct {
	value *PreviewInboundMappingRequest
	isSet bool
}

func (v NullablePreviewInboundMappingRequest) Get() *PreviewInboundMappingRequest {
	return v.value
}

func (v *NullablePreviewInboundMappingRequest) Set(val *PreviewInboundMappingRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePreviewInboundMappingRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePreviewInboundMappingRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePreviewInboundMappingRequest(val *PreviewInboundMappingRequest) *NullablePreviewInboundMappingRequest {
	return &NullablePreviewInboundMappingRequest{value: val, isSet: true}
}

func (v NullablePreviewInboundMappingRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePreviewInboundMappingRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


