/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
)

// checks if the ResolvedAggregateBlockResponseGroupsInnerKeyInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResolvedAggregateBlockResponseGroupsInnerKeyInner{}

// ResolvedAggregateBlockResponseGroupsInnerKeyInner struct for ResolvedAggregateBlockResponseGroupsInnerKeyInner
type ResolvedAggregateBlockResponseGroupsInnerKeyInner struct {
	Field *string `json:"field,omitempty"`
	Value interface{} `json:"value,omitempty"`
	// Display label, for list and reference fields
	CustomValue NullableString `json:"custom_value,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ResolvedAggregateBlockResponseGroupsInnerKeyInner ResolvedAggregateBlockResponseGroupsInnerKeyInner

// NewResolvedAggregateBlockResponseGroupsInnerKeyInner instantiates a new ResolvedAggregateBlockResponseGroupsInnerKeyInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResolvedAggregateBlockResponseGroupsInnerKeyInner() *ResolvedAggregateBlockResponseGroupsInnerKeyInner {
	this := ResolvedAggregateBlockResponseGroupsInnerKeyInner{}
	return &this
}

// NewResolvedAggregateBlockResponseGroupsInnerKeyInnerWithDefaults instantiates a new ResolvedAggregateBlockResponseGroupsInnerKeyInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResolvedAggregateBlockResponseGroupsInnerKeyInnerWithDefaults() *ResolvedAggregateBlockResponseGroupsInnerKeyInner {
	this := ResolvedAggregateBlockResponseGroupsInnerKeyInner{}
	return &this
}

// GetField returns the Field field value if set, zero value otherwise.
func (o *ResolvedAggregateBlockResponseGroupsInnerKeyInner) GetField() string {
	if o == nil || IsNil(o.Field) {
		var ret string
		return ret
	}
	return *o.Field
}

// GetFieldOk returns a tuple with the Field field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResolvedAggregateBlockResponseGroupsInnerKeyInner) GetFieldOk() (*string, bool) {
	if o == nil || IsNil(o.Field) {
		return nil, false
	}
	return o.Field, true
}

// HasField returns a boolean if a field has been set.
func (o *ResolvedAggregateBlockResponseGroupsInnerKeyInner) HasField() bool {
	if o != nil && !IsNil(o.Field) {
		return true
	}

	return false
}

// SetField gets a reference to the given string and assigns it to the Field field.
func (o *ResolvedAggregateBlockResponseGroupsInnerKeyInner) SetField(v string) {
	o.Field = &v
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ResolvedAggregateBlockResponseGroupsInnerKeyInner) GetValue() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResolvedAggregateBlockResponseGroupsInnerKeyInner) GetValueOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return &o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ResolvedAggregateBlockResponseGroupsInnerKeyInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given interface{} and assigns it to the Value field.
func (o *ResolvedAggregateBlockResponseGroupsInnerKeyInner) SetValue(v interface{}) {
	o.Value = v
}

// GetCustomValue returns the CustomValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ResolvedAggregateBlockResponseGroupsInnerKeyInner) GetCustomValue() string {
	if o == nil || IsNil(o.CustomValue.Get()) {
		var ret string
		return ret
	}
	return *o.CustomValue.Get()
}

// GetCustomValueOk returns a tuple with the CustomValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResolvedAggregateBlockResponseGroupsInnerKeyInner) GetCustomValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomValue.Get(), o.CustomValue.IsSet()
}

// HasCustomValue returns a boolean if a field has been set.
func (o *ResolvedAggregateBlockResponseGroupsInnerKeyInner) HasCustomValue() bool {
	if o != nil && o.CustomValue.IsSet() {
		return true
	}

	return false
}

// SetCustomValue gets a reference to the given NullableString and assigns it to the CustomValue field.
func (o *ResolvedAggregateBlockResponseGroupsInnerKeyInner) SetCustomValue(v string) {
	o.CustomValue.Set(&v)
}
// SetCustomValueNil sets the value for CustomValue to be an explicit nil
func (o *ResolvedAggregateBlockResponseGroupsInnerKeyInner) SetCustomValueNil() {
	o.CustomValue.Set(nil)
}

// UnsetCustomValue ensures that no value is present for CustomValue, not even an explicit nil
func (o *ResolvedAggregateBlockResponseGroupsInnerKeyInner) UnsetCustomValue() {
	o.CustomValue.Unset()
}

func (o ResolvedAggregateBlockResponseGroupsInnerKeyInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResolvedAggregateBlockResponseGroupsInnerKeyInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Field) {
		toSerialize["field"] = o.Field
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	if o.CustomValue.IsSet() {
		toSerialize["custom_value"] = o.CustomValue.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ResolvedAggregateBlockResponseGroupsInnerKeyInner) UnmarshalJSON(data []byte) (err error) {
	varResolvedAggregateBlockResponseGroupsInnerKeyInner := _ResolvedAggregateBlockResponseGroupsInnerKeyInner{}

	err = json.Unmarshal(data, &varResolvedAggregateBlockResponseGroupsInnerKeyInner)

	if err != nil {
		return err
	}

	*o = ResolvedAggregateBlockResponseGroupsInnerKeyInner(varResolvedAggregateBlockResponseGroupsInnerKeyInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "field")
		delete(additionalProperties, "value")
		delete(additionalProperties, "custom_value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableResolvedAggregateBlockResponseGroupsInnerKeyInner struct {
	value *ResolvedAggregateBlockResponseGroupsInnerKeyInner
	isSet bool
}

func (v NullableResolvedAggregateBlockResponseGroupsInnerKeyInner) Get() *ResolvedAggregateBlockResponseGroupsInnerKeyInner {
	return v.value
}

func (v *NullableResolvedAggregateBlockResponseGroupsInnerKeyInner) Set(val *ResolvedAggregateBlockResponseGroupsInnerKeyInner) {
	v.value = val
	v.isSet = true
}

func (v NullableResolvedAggregateBlockResponseGroupsInnerKeyInner) IsSet() bool {
	return v.isSet
}

func (v *NullableResolvedAggregateBlockResponseGroupsInnerKeyInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResolvedAggregateBlockResponseGroupsInnerKeyInner(val *ResolvedAggregateBlockResponseGroupsInnerKeyInner) *NullableResolvedAggregateBlockResponseGroupsInnerKeyInner {
	return &NullableResolvedAggregateBlockResponseGroupsInnerKeyInner{value: val, isSet: true}
}

func (v NullableResolvedAggregateBlockResponseGroupsInnerKeyInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResolvedAggregateBlockResponseGroupsInnerKeyInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


