/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the EntityRuleOverviewResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntityRuleOverviewResponse{}

// EntityRuleOverviewResponse Template-scoped validation rule. All writes must satisfy active rules.
type EntityRuleOverviewResponse struct {
	// Rule UUID
	Id string `json:"id"`
	// Short rule name
	Name string `json:"name"`
	// Error message returned on violation
	Message string `json:"message"`
	// Whether the rule is actively enforced
	IsEnabled bool `json:"is_enabled"`
	// Activating conditions; empty means unconditional
	When []EntityRulePredicateOverviewResponse `json:"when"`
	// Enforced constraints
	Then []EntityRulePredicateOverviewResponse `json:"then"`
	AdditionalProperties map[string]interface{}
}

type _EntityRuleOverviewResponse EntityRuleOverviewResponse

// NewEntityRuleOverviewResponse instantiates a new EntityRuleOverviewResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntityRuleOverviewResponse(id string, name string, message string, isEnabled bool, when []EntityRulePredicateOverviewResponse, then []EntityRulePredicateOverviewResponse) *EntityRuleOverviewResponse {
	this := EntityRuleOverviewResponse{}
	this.Id = id
	this.Name = name
	this.Message = message
	this.IsEnabled = isEnabled
	this.When = when
	this.Then = then
	return &this
}

// NewEntityRuleOverviewResponseWithDefaults instantiates a new EntityRuleOverviewResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntityRuleOverviewResponseWithDefaults() *EntityRuleOverviewResponse {
	this := EntityRuleOverviewResponse{}
	return &this
}

// GetId returns the Id field value
func (o *EntityRuleOverviewResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EntityRuleOverviewResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EntityRuleOverviewResponse) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *EntityRuleOverviewResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EntityRuleOverviewResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EntityRuleOverviewResponse) SetName(v string) {
	o.Name = v
}

// GetMessage returns the Message field value
func (o *EntityRuleOverviewResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *EntityRuleOverviewResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *EntityRuleOverviewResponse) SetMessage(v string) {
	o.Message = v
}

// GetIsEnabled returns the IsEnabled field value
func (o *EntityRuleOverviewResponse) GetIsEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value
// and a boolean to check if the value has been set.
func (o *EntityRuleOverviewResponse) GetIsEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsEnabled, true
}

// SetIsEnabled sets field value
func (o *EntityRuleOverviewResponse) SetIsEnabled(v bool) {
	o.IsEnabled = v
}

// GetWhen returns the When field value
func (o *EntityRuleOverviewResponse) GetWhen() []EntityRulePredicateOverviewResponse {
	if o == nil {
		var ret []EntityRulePredicateOverviewResponse
		return ret
	}

	return o.When
}

// GetWhenOk returns a tuple with the When field value
// and a boolean to check if the value has been set.
func (o *EntityRuleOverviewResponse) GetWhenOk() ([]EntityRulePredicateOverviewResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.When, true
}

// SetWhen sets field value
func (o *EntityRuleOverviewResponse) SetWhen(v []EntityRulePredicateOverviewResponse) {
	o.When = v
}

// GetThen returns the Then field value
func (o *EntityRuleOverviewResponse) GetThen() []EntityRulePredicateOverviewResponse {
	if o == nil {
		var ret []EntityRulePredicateOverviewResponse
		return ret
	}

	return o.Then
}

// GetThenOk returns a tuple with the Then field value
// and a boolean to check if the value has been set.
func (o *EntityRuleOverviewResponse) GetThenOk() ([]EntityRulePredicateOverviewResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Then, true
}

// SetThen sets field value
func (o *EntityRuleOverviewResponse) SetThen(v []EntityRulePredicateOverviewResponse) {
	o.Then = v
}

func (o EntityRuleOverviewResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntityRuleOverviewResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["message"] = o.Message
	toSerialize["is_enabled"] = o.IsEnabled
	toSerialize["when"] = o.When
	toSerialize["then"] = o.Then

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EntityRuleOverviewResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"message",
		"is_enabled",
		"when",
		"then",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEntityRuleOverviewResponse := _EntityRuleOverviewResponse{}

	err = json.Unmarshal(data, &varEntityRuleOverviewResponse)

	if err != nil {
		return err
	}

	*o = EntityRuleOverviewResponse(varEntityRuleOverviewResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "message")
		delete(additionalProperties, "is_enabled")
		delete(additionalProperties, "when")
		delete(additionalProperties, "then")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEntityRuleOverviewResponse struct {
	value *EntityRuleOverviewResponse
	isSet bool
}

func (v NullableEntityRuleOverviewResponse) Get() *EntityRuleOverviewResponse {
	return v.value
}

func (v *NullableEntityRuleOverviewResponse) Set(val *EntityRuleOverviewResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEntityRuleOverviewResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEntityRuleOverviewResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntityRuleOverviewResponse(val *EntityRuleOverviewResponse) *NullableEntityRuleOverviewResponse {
	return &NullableEntityRuleOverviewResponse{value: val, isSet: true}
}

func (v NullableEntityRuleOverviewResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntityRuleOverviewResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


