/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the AssignUserToProjectRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssignUserToProjectRequest{}

// AssignUserToProjectRequest struct for AssignUserToProjectRequest
type AssignUserToProjectRequest struct {
	UserId string `json:"user_id"`
	// The Role ID to assign
	RoleId string `json:"role_id"`
	AdditionalProperties map[string]interface{}
}

type _AssignUserToProjectRequest AssignUserToProjectRequest

// NewAssignUserToProjectRequest instantiates a new AssignUserToProjectRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssignUserToProjectRequest(userId string, roleId string) *AssignUserToProjectRequest {
	this := AssignUserToProjectRequest{}
	this.UserId = userId
	this.RoleId = roleId
	return &this
}

// NewAssignUserToProjectRequestWithDefaults instantiates a new AssignUserToProjectRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssignUserToProjectRequestWithDefaults() *AssignUserToProjectRequest {
	this := AssignUserToProjectRequest{}
	return &this
}

// GetUserId returns the UserId field value
func (o *AssignUserToProjectRequest) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *AssignUserToProjectRequest) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *AssignUserToProjectRequest) SetUserId(v string) {
	o.UserId = v
}

// GetRoleId returns the RoleId field value
func (o *AssignUserToProjectRequest) GetRoleId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoleId
}

// GetRoleIdOk returns a tuple with the RoleId field value
// and a boolean to check if the value has been set.
func (o *AssignUserToProjectRequest) GetRoleIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoleId, true
}

// SetRoleId sets field value
func (o *AssignUserToProjectRequest) SetRoleId(v string) {
	o.RoleId = v
}

func (o AssignUserToProjectRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssignUserToProjectRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user_id"] = o.UserId
	toSerialize["role_id"] = o.RoleId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AssignUserToProjectRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_id",
		"role_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssignUserToProjectRequest := _AssignUserToProjectRequest{}

	err = json.Unmarshal(data, &varAssignUserToProjectRequest)

	if err != nil {
		return err
	}

	*o = AssignUserToProjectRequest(varAssignUserToProjectRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "user_id")
		delete(additionalProperties, "role_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAssignUserToProjectRequest struct {
	value *AssignUserToProjectRequest
	isSet bool
}

func (v NullableAssignUserToProjectRequest) Get() *AssignUserToProjectRequest {
	return v.value
}

func (v *NullableAssignUserToProjectRequest) Set(val *AssignUserToProjectRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAssignUserToProjectRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAssignUserToProjectRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssignUserToProjectRequest(val *AssignUserToProjectRequest) *NullableAssignUserToProjectRequest {
	return &NullableAssignUserToProjectRequest{value: val, isSet: true}
}

func (v NullableAssignUserToProjectRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssignUserToProjectRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


