/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
	"time"
)

// checks if the UpdateEntityRequestAttributeValuesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateEntityRequestAttributeValuesInner{}

// UpdateEntityRequestAttributeValuesInner struct for UpdateEntityRequestAttributeValuesInner
type UpdateEntityRequestAttributeValuesInner struct {
	// Target attribute UUID (provide either attribute_id or attribute_slug)
	AttributeId NullableString `json:"attribute_id,omitempty"`
	// Target attribute slug identifier (provide either attribute_id or attribute_slug)
	AttributeSlug NullableString `json:"attribute_slug,omitempty"`
	// Serialized attribute value. Formats: String (\"Sample\"), Number (\"123.45\"), Boolean (\"true\"|\"false\"), Date (\"YYYY-MM-DD\"), Datetime (\"YYYY-MM-DD HH:MM:SS\"), List (ListItem UUID), Reference (target Entity UUID)
	Value *string `json:"value,omitempty"`
	// Observation or mutation timestamp in ISO 8601 or YYYY-MM-DD HH:MM:SS format. Defaults to current UTC time if omitted.
	UpdatedAt NullableTime `json:"updated_at,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateEntityRequestAttributeValuesInner UpdateEntityRequestAttributeValuesInner

// NewUpdateEntityRequestAttributeValuesInner instantiates a new UpdateEntityRequestAttributeValuesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateEntityRequestAttributeValuesInner() *UpdateEntityRequestAttributeValuesInner {
	this := UpdateEntityRequestAttributeValuesInner{}
	return &this
}

// NewUpdateEntityRequestAttributeValuesInnerWithDefaults instantiates a new UpdateEntityRequestAttributeValuesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateEntityRequestAttributeValuesInnerWithDefaults() *UpdateEntityRequestAttributeValuesInner {
	this := UpdateEntityRequestAttributeValuesInner{}
	return &this
}

// GetAttributeId returns the AttributeId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateEntityRequestAttributeValuesInner) GetAttributeId() string {
	if o == nil || IsNil(o.AttributeId.Get()) {
		var ret string
		return ret
	}
	return *o.AttributeId.Get()
}

// GetAttributeIdOk returns a tuple with the AttributeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateEntityRequestAttributeValuesInner) GetAttributeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AttributeId.Get(), o.AttributeId.IsSet()
}

// HasAttributeId returns a boolean if a field has been set.
func (o *UpdateEntityRequestAttributeValuesInner) HasAttributeId() bool {
	if o != nil && o.AttributeId.IsSet() {
		return true
	}

	return false
}

// SetAttributeId gets a reference to the given NullableString and assigns it to the AttributeId field.
func (o *UpdateEntityRequestAttributeValuesInner) SetAttributeId(v string) {
	o.AttributeId.Set(&v)
}
// SetAttributeIdNil sets the value for AttributeId to be an explicit nil
func (o *UpdateEntityRequestAttributeValuesInner) SetAttributeIdNil() {
	o.AttributeId.Set(nil)
}

// UnsetAttributeId ensures that no value is present for AttributeId, not even an explicit nil
func (o *UpdateEntityRequestAttributeValuesInner) UnsetAttributeId() {
	o.AttributeId.Unset()
}

// GetAttributeSlug returns the AttributeSlug field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateEntityRequestAttributeValuesInner) GetAttributeSlug() string {
	if o == nil || IsNil(o.AttributeSlug.Get()) {
		var ret string
		return ret
	}
	return *o.AttributeSlug.Get()
}

// GetAttributeSlugOk returns a tuple with the AttributeSlug field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateEntityRequestAttributeValuesInner) GetAttributeSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AttributeSlug.Get(), o.AttributeSlug.IsSet()
}

// HasAttributeSlug returns a boolean if a field has been set.
func (o *UpdateEntityRequestAttributeValuesInner) HasAttributeSlug() bool {
	if o != nil && o.AttributeSlug.IsSet() {
		return true
	}

	return false
}

// SetAttributeSlug gets a reference to the given NullableString and assigns it to the AttributeSlug field.
func (o *UpdateEntityRequestAttributeValuesInner) SetAttributeSlug(v string) {
	o.AttributeSlug.Set(&v)
}
// SetAttributeSlugNil sets the value for AttributeSlug to be an explicit nil
func (o *UpdateEntityRequestAttributeValuesInner) SetAttributeSlugNil() {
	o.AttributeSlug.Set(nil)
}

// UnsetAttributeSlug ensures that no value is present for AttributeSlug, not even an explicit nil
func (o *UpdateEntityRequestAttributeValuesInner) UnsetAttributeSlug() {
	o.AttributeSlug.Unset()
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *UpdateEntityRequestAttributeValuesInner) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntityRequestAttributeValuesInner) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *UpdateEntityRequestAttributeValuesInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *UpdateEntityRequestAttributeValuesInner) SetValue(v string) {
	o.Value = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateEntityRequestAttributeValuesInner) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateEntityRequestAttributeValuesInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *UpdateEntityRequestAttributeValuesInner) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableTime and assigns it to the UpdatedAt field.
func (o *UpdateEntityRequestAttributeValuesInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}
// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *UpdateEntityRequestAttributeValuesInner) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *UpdateEntityRequestAttributeValuesInner) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

func (o UpdateEntityRequestAttributeValuesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateEntityRequestAttributeValuesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AttributeId.IsSet() {
		toSerialize["attribute_id"] = o.AttributeId.Get()
	}
	if o.AttributeSlug.IsSet() {
		toSerialize["attribute_slug"] = o.AttributeSlug.Get()
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if o.UpdatedAt.IsSet() {
		toSerialize["updated_at"] = o.UpdatedAt.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateEntityRequestAttributeValuesInner) UnmarshalJSON(data []byte) (err error) {
	varUpdateEntityRequestAttributeValuesInner := _UpdateEntityRequestAttributeValuesInner{}

	err = json.Unmarshal(data, &varUpdateEntityRequestAttributeValuesInner)

	if err != nil {
		return err
	}

	*o = UpdateEntityRequestAttributeValuesInner(varUpdateEntityRequestAttributeValuesInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "attribute_id")
		delete(additionalProperties, "attribute_slug")
		delete(additionalProperties, "value")
		delete(additionalProperties, "updated_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateEntityRequestAttributeValuesInner struct {
	value *UpdateEntityRequestAttributeValuesInner
	isSet bool
}

func (v NullableUpdateEntityRequestAttributeValuesInner) Get() *UpdateEntityRequestAttributeValuesInner {
	return v.value
}

func (v *NullableUpdateEntityRequestAttributeValuesInner) Set(val *UpdateEntityRequestAttributeValuesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateEntityRequestAttributeValuesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateEntityRequestAttributeValuesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateEntityRequestAttributeValuesInner(val *UpdateEntityRequestAttributeValuesInner) *NullableUpdateEntityRequestAttributeValuesInner {
	return &NullableUpdateEntityRequestAttributeValuesInner{value: val, isSet: true}
}

func (v NullableUpdateEntityRequestAttributeValuesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateEntityRequestAttributeValuesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


