/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the EntityRulePredicate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntityRulePredicate{}

// EntityRulePredicate One predicate over an attribute's current value. Used both as a `when` condition and as a `then` constraint.
type EntityRulePredicate struct {
	// Attribute UUID the predicate reads
	AttributeId string `json:"attribute_id"`
	// Comparison operator. `gt`/`gte`/`lt`/`lte` apply to number and date attributes, `contains`/`not_contains` to text, `in` to list attributes (value is a list of list item UUIDs), `eq`/`neq`/`is_empty`/`is_not_empty` to every non-metric attribute.
	Operator string `json:"operator"`
	Value NullableEntityRulePredicateValue `json:"value,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _EntityRulePredicate EntityRulePredicate

// NewEntityRulePredicate instantiates a new EntityRulePredicate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntityRulePredicate(attributeId string, operator string) *EntityRulePredicate {
	this := EntityRulePredicate{}
	this.AttributeId = attributeId
	this.Operator = operator
	return &this
}

// NewEntityRulePredicateWithDefaults instantiates a new EntityRulePredicate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntityRulePredicateWithDefaults() *EntityRulePredicate {
	this := EntityRulePredicate{}
	return &this
}

// GetAttributeId returns the AttributeId field value
func (o *EntityRulePredicate) GetAttributeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AttributeId
}

// GetAttributeIdOk returns a tuple with the AttributeId field value
// and a boolean to check if the value has been set.
func (o *EntityRulePredicate) GetAttributeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttributeId, true
}

// SetAttributeId sets field value
func (o *EntityRulePredicate) SetAttributeId(v string) {
	o.AttributeId = v
}

// GetOperator returns the Operator field value
func (o *EntityRulePredicate) GetOperator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value
// and a boolean to check if the value has been set.
func (o *EntityRulePredicate) GetOperatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operator, true
}

// SetOperator sets field value
func (o *EntityRulePredicate) SetOperator(v string) {
	o.Operator = v
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EntityRulePredicate) GetValue() EntityRulePredicateValue {
	if o == nil || IsNil(o.Value.Get()) {
		var ret EntityRulePredicateValue
		return ret
	}
	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EntityRulePredicate) GetValueOk() (*EntityRulePredicateValue, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// HasValue returns a boolean if a field has been set.
func (o *EntityRulePredicate) HasValue() bool {
	if o != nil && o.Value.IsSet() {
		return true
	}

	return false
}

// SetValue gets a reference to the given NullableEntityRulePredicateValue and assigns it to the Value field.
func (o *EntityRulePredicate) SetValue(v EntityRulePredicateValue) {
	o.Value.Set(&v)
}
// SetValueNil sets the value for Value to be an explicit nil
func (o *EntityRulePredicate) SetValueNil() {
	o.Value.Set(nil)
}

// UnsetValue ensures that no value is present for Value, not even an explicit nil
func (o *EntityRulePredicate) UnsetValue() {
	o.Value.Unset()
}

func (o EntityRulePredicate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntityRulePredicate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attribute_id"] = o.AttributeId
	toSerialize["operator"] = o.Operator
	if o.Value.IsSet() {
		toSerialize["value"] = o.Value.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EntityRulePredicate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attribute_id",
		"operator",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEntityRulePredicate := _EntityRulePredicate{}

	err = json.Unmarshal(data, &varEntityRulePredicate)

	if err != nil {
		return err
	}

	*o = EntityRulePredicate(varEntityRulePredicate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "attribute_id")
		delete(additionalProperties, "operator")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEntityRulePredicate struct {
	value *EntityRulePredicate
	isSet bool
}

func (v NullableEntityRulePredicate) Get() *EntityRulePredicate {
	return v.value
}

func (v *NullableEntityRulePredicate) Set(val *EntityRulePredicate) {
	v.value = val
	v.isSet = true
}

func (v NullableEntityRulePredicate) IsSet() bool {
	return v.isSet
}

func (v *NullableEntityRulePredicate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntityRulePredicate(val *EntityRulePredicate) *NullableEntityRulePredicate {
	return &NullableEntityRulePredicate{value: val, isSet: true}
}

func (v NullableEntityRulePredicate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntityRulePredicate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


