/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.15
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the ValidationErrorResponseViolationsInnerRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidationErrorResponseViolationsInnerRule{}

// ValidationErrorResponseViolationsInnerRule struct for ValidationErrorResponseViolationsInnerRule
type ValidationErrorResponseViolationsInnerRule struct {
	Id string `json:"id"`
	Name string `json:"name"`
	AdditionalProperties map[string]interface{}
}

type _ValidationErrorResponseViolationsInnerRule ValidationErrorResponseViolationsInnerRule

// NewValidationErrorResponseViolationsInnerRule instantiates a new ValidationErrorResponseViolationsInnerRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidationErrorResponseViolationsInnerRule(id string, name string) *ValidationErrorResponseViolationsInnerRule {
	this := ValidationErrorResponseViolationsInnerRule{}
	this.Id = id
	this.Name = name
	return &this
}

// NewValidationErrorResponseViolationsInnerRuleWithDefaults instantiates a new ValidationErrorResponseViolationsInnerRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidationErrorResponseViolationsInnerRuleWithDefaults() *ValidationErrorResponseViolationsInnerRule {
	this := ValidationErrorResponseViolationsInnerRule{}
	return &this
}

// GetId returns the Id field value
func (o *ValidationErrorResponseViolationsInnerRule) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ValidationErrorResponseViolationsInnerRule) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ValidationErrorResponseViolationsInnerRule) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ValidationErrorResponseViolationsInnerRule) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ValidationErrorResponseViolationsInnerRule) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ValidationErrorResponseViolationsInnerRule) SetName(v string) {
	o.Name = v
}

func (o ValidationErrorResponseViolationsInnerRule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidationErrorResponseViolationsInnerRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ValidationErrorResponseViolationsInnerRule) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varValidationErrorResponseViolationsInnerRule := _ValidationErrorResponseViolationsInnerRule{}

	err = json.Unmarshal(data, &varValidationErrorResponseViolationsInnerRule)

	if err != nil {
		return err
	}

	*o = ValidationErrorResponseViolationsInnerRule(varValidationErrorResponseViolationsInnerRule)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableValidationErrorResponseViolationsInnerRule struct {
	value *ValidationErrorResponseViolationsInnerRule
	isSet bool
}

func (v NullableValidationErrorResponseViolationsInnerRule) Get() *ValidationErrorResponseViolationsInnerRule {
	return v.value
}

func (v *NullableValidationErrorResponseViolationsInnerRule) Set(val *ValidationErrorResponseViolationsInnerRule) {
	v.value = val
	v.isSet = true
}

func (v NullableValidationErrorResponseViolationsInnerRule) IsSet() bool {
	return v.isSet
}

func (v *NullableValidationErrorResponseViolationsInnerRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidationErrorResponseViolationsInnerRule(val *ValidationErrorResponseViolationsInnerRule) *NullableValidationErrorResponseViolationsInnerRule {
	return &NullableValidationErrorResponseViolationsInnerRule{value: val, isSet: true}
}

func (v NullableValidationErrorResponseViolationsInnerRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidationErrorResponseViolationsInnerRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


