/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismith-sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateAutomationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAutomationRequest{}

// CreateAutomationRequest struct for CreateAutomationRequest
type CreateAutomationRequest struct {
	Name string `json:"name"`
	Description NullableString `json:"description,omitempty"`
	Trigger CreateAutomationRequestTrigger `json:"trigger"`
	Conditions []CreateAutomationRequestConditionsInner `json:"conditions"`
	Actions []CreateAutomationRequestActionsInner `json:"actions"`
	CooldownSeconds NullableInt32 `json:"cooldownSeconds,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateAutomationRequest CreateAutomationRequest

// NewCreateAutomationRequest instantiates a new CreateAutomationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAutomationRequest(name string, trigger CreateAutomationRequestTrigger, conditions []CreateAutomationRequestConditionsInner, actions []CreateAutomationRequestActionsInner) *CreateAutomationRequest {
	this := CreateAutomationRequest{}
	this.Name = name
	this.Trigger = trigger
	this.Conditions = conditions
	this.Actions = actions
	return &this
}

// NewCreateAutomationRequestWithDefaults instantiates a new CreateAutomationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAutomationRequestWithDefaults() *CreateAutomationRequest {
	this := CreateAutomationRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateAutomationRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateAutomationRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateAutomationRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAutomationRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAutomationRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateAutomationRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *CreateAutomationRequest) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *CreateAutomationRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *CreateAutomationRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetTrigger returns the Trigger field value
func (o *CreateAutomationRequest) GetTrigger() CreateAutomationRequestTrigger {
	if o == nil {
		var ret CreateAutomationRequestTrigger
		return ret
	}

	return o.Trigger
}

// GetTriggerOk returns a tuple with the Trigger field value
// and a boolean to check if the value has been set.
func (o *CreateAutomationRequest) GetTriggerOk() (*CreateAutomationRequestTrigger, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Trigger, true
}

// SetTrigger sets field value
func (o *CreateAutomationRequest) SetTrigger(v CreateAutomationRequestTrigger) {
	o.Trigger = v
}

// GetConditions returns the Conditions field value
func (o *CreateAutomationRequest) GetConditions() []CreateAutomationRequestConditionsInner {
	if o == nil {
		var ret []CreateAutomationRequestConditionsInner
		return ret
	}

	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value
// and a boolean to check if the value has been set.
func (o *CreateAutomationRequest) GetConditionsOk() ([]CreateAutomationRequestConditionsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Conditions, true
}

// SetConditions sets field value
func (o *CreateAutomationRequest) SetConditions(v []CreateAutomationRequestConditionsInner) {
	o.Conditions = v
}

// GetActions returns the Actions field value
func (o *CreateAutomationRequest) GetActions() []CreateAutomationRequestActionsInner {
	if o == nil {
		var ret []CreateAutomationRequestActionsInner
		return ret
	}

	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value
// and a boolean to check if the value has been set.
func (o *CreateAutomationRequest) GetActionsOk() ([]CreateAutomationRequestActionsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Actions, true
}

// SetActions sets field value
func (o *CreateAutomationRequest) SetActions(v []CreateAutomationRequestActionsInner) {
	o.Actions = v
}

// GetCooldownSeconds returns the CooldownSeconds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAutomationRequest) GetCooldownSeconds() int32 {
	if o == nil || IsNil(o.CooldownSeconds.Get()) {
		var ret int32
		return ret
	}
	return *o.CooldownSeconds.Get()
}

// GetCooldownSecondsOk returns a tuple with the CooldownSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAutomationRequest) GetCooldownSecondsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CooldownSeconds.Get(), o.CooldownSeconds.IsSet()
}

// HasCooldownSeconds returns a boolean if a field has been set.
func (o *CreateAutomationRequest) HasCooldownSeconds() bool {
	if o != nil && o.CooldownSeconds.IsSet() {
		return true
	}

	return false
}

// SetCooldownSeconds gets a reference to the given NullableInt32 and assigns it to the CooldownSeconds field.
func (o *CreateAutomationRequest) SetCooldownSeconds(v int32) {
	o.CooldownSeconds.Set(&v)
}
// SetCooldownSecondsNil sets the value for CooldownSeconds to be an explicit nil
func (o *CreateAutomationRequest) SetCooldownSecondsNil() {
	o.CooldownSeconds.Set(nil)
}

// UnsetCooldownSeconds ensures that no value is present for CooldownSeconds, not even an explicit nil
func (o *CreateAutomationRequest) UnsetCooldownSeconds() {
	o.CooldownSeconds.Unset()
}

func (o CreateAutomationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAutomationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	toSerialize["trigger"] = o.Trigger
	toSerialize["conditions"] = o.Conditions
	toSerialize["actions"] = o.Actions
	if o.CooldownSeconds.IsSet() {
		toSerialize["cooldownSeconds"] = o.CooldownSeconds.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateAutomationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"trigger",
		"conditions",
		"actions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAutomationRequest := _CreateAutomationRequest{}

	err = json.Unmarshal(data, &varCreateAutomationRequest)

	if err != nil {
		return err
	}

	*o = CreateAutomationRequest(varCreateAutomationRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "trigger")
		delete(additionalProperties, "conditions")
		delete(additionalProperties, "actions")
		delete(additionalProperties, "cooldownSeconds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateAutomationRequest struct {
	value *CreateAutomationRequest
	isSet bool
}

func (v NullableCreateAutomationRequest) Get() *CreateAutomationRequest {
	return v.value
}

func (v *NullableCreateAutomationRequest) Set(val *CreateAutomationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAutomationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAutomationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAutomationRequest(val *CreateAutomationRequest) *NullableCreateAutomationRequest {
	return &NullableCreateAutomationRequest{value: val, isSet: true}
}

func (v NullableCreateAutomationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAutomationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


