/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the EntityActionFieldOverviewResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntityActionFieldOverviewResponse{}

// EntityActionFieldOverviewResponse Field required or prompted from the operator when executing this action.
type EntityActionFieldOverviewResponse struct {
	// Attribute UUID to set
	AttributeId string `json:"attribute_id"`
	// Attribute slug identifier
	AttributeSlug NullableString `json:"attribute_slug,omitempty"`
	// Whether the field must be supplied
	Required bool `json:"required"`
	// Guidance text for the operator
	Hint NullableString `json:"hint,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _EntityActionFieldOverviewResponse EntityActionFieldOverviewResponse

// NewEntityActionFieldOverviewResponse instantiates a new EntityActionFieldOverviewResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntityActionFieldOverviewResponse(attributeId string, required bool) *EntityActionFieldOverviewResponse {
	this := EntityActionFieldOverviewResponse{}
	this.AttributeId = attributeId
	this.Required = required
	return &this
}

// NewEntityActionFieldOverviewResponseWithDefaults instantiates a new EntityActionFieldOverviewResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntityActionFieldOverviewResponseWithDefaults() *EntityActionFieldOverviewResponse {
	this := EntityActionFieldOverviewResponse{}
	return &this
}

// GetAttributeId returns the AttributeId field value
func (o *EntityActionFieldOverviewResponse) GetAttributeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AttributeId
}

// GetAttributeIdOk returns a tuple with the AttributeId field value
// and a boolean to check if the value has been set.
func (o *EntityActionFieldOverviewResponse) GetAttributeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttributeId, true
}

// SetAttributeId sets field value
func (o *EntityActionFieldOverviewResponse) SetAttributeId(v string) {
	o.AttributeId = v
}

// GetAttributeSlug returns the AttributeSlug field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EntityActionFieldOverviewResponse) GetAttributeSlug() string {
	if o == nil || IsNil(o.AttributeSlug.Get()) {
		var ret string
		return ret
	}
	return *o.AttributeSlug.Get()
}

// GetAttributeSlugOk returns a tuple with the AttributeSlug field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EntityActionFieldOverviewResponse) GetAttributeSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AttributeSlug.Get(), o.AttributeSlug.IsSet()
}

// HasAttributeSlug returns a boolean if a field has been set.
func (o *EntityActionFieldOverviewResponse) HasAttributeSlug() bool {
	if o != nil && o.AttributeSlug.IsSet() {
		return true
	}

	return false
}

// SetAttributeSlug gets a reference to the given NullableString and assigns it to the AttributeSlug field.
func (o *EntityActionFieldOverviewResponse) SetAttributeSlug(v string) {
	o.AttributeSlug.Set(&v)
}
// SetAttributeSlugNil sets the value for AttributeSlug to be an explicit nil
func (o *EntityActionFieldOverviewResponse) SetAttributeSlugNil() {
	o.AttributeSlug.Set(nil)
}

// UnsetAttributeSlug ensures that no value is present for AttributeSlug, not even an explicit nil
func (o *EntityActionFieldOverviewResponse) UnsetAttributeSlug() {
	o.AttributeSlug.Unset()
}

// GetRequired returns the Required field value
func (o *EntityActionFieldOverviewResponse) GetRequired() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Required
}

// GetRequiredOk returns a tuple with the Required field value
// and a boolean to check if the value has been set.
func (o *EntityActionFieldOverviewResponse) GetRequiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Required, true
}

// SetRequired sets field value
func (o *EntityActionFieldOverviewResponse) SetRequired(v bool) {
	o.Required = v
}

// GetHint returns the Hint field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EntityActionFieldOverviewResponse) GetHint() string {
	if o == nil || IsNil(o.Hint.Get()) {
		var ret string
		return ret
	}
	return *o.Hint.Get()
}

// GetHintOk returns a tuple with the Hint field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EntityActionFieldOverviewResponse) GetHintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Hint.Get(), o.Hint.IsSet()
}

// HasHint returns a boolean if a field has been set.
func (o *EntityActionFieldOverviewResponse) HasHint() bool {
	if o != nil && o.Hint.IsSet() {
		return true
	}

	return false
}

// SetHint gets a reference to the given NullableString and assigns it to the Hint field.
func (o *EntityActionFieldOverviewResponse) SetHint(v string) {
	o.Hint.Set(&v)
}
// SetHintNil sets the value for Hint to be an explicit nil
func (o *EntityActionFieldOverviewResponse) SetHintNil() {
	o.Hint.Set(nil)
}

// UnsetHint ensures that no value is present for Hint, not even an explicit nil
func (o *EntityActionFieldOverviewResponse) UnsetHint() {
	o.Hint.Unset()
}

func (o EntityActionFieldOverviewResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntityActionFieldOverviewResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attribute_id"] = o.AttributeId
	if o.AttributeSlug.IsSet() {
		toSerialize["attribute_slug"] = o.AttributeSlug.Get()
	}
	toSerialize["required"] = o.Required
	if o.Hint.IsSet() {
		toSerialize["hint"] = o.Hint.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EntityActionFieldOverviewResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attribute_id",
		"required",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEntityActionFieldOverviewResponse := _EntityActionFieldOverviewResponse{}

	err = json.Unmarshal(data, &varEntityActionFieldOverviewResponse)

	if err != nil {
		return err
	}

	*o = EntityActionFieldOverviewResponse(varEntityActionFieldOverviewResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "attribute_id")
		delete(additionalProperties, "attribute_slug")
		delete(additionalProperties, "required")
		delete(additionalProperties, "hint")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEntityActionFieldOverviewResponse struct {
	value *EntityActionFieldOverviewResponse
	isSet bool
}

func (v NullableEntityActionFieldOverviewResponse) Get() *EntityActionFieldOverviewResponse {
	return v.value
}

func (v *NullableEntityActionFieldOverviewResponse) Set(val *EntityActionFieldOverviewResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEntityActionFieldOverviewResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEntityActionFieldOverviewResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntityActionFieldOverviewResponse(val *EntityActionFieldOverviewResponse) *NullableEntityActionFieldOverviewResponse {
	return &NullableEntityActionFieldOverviewResponse{value: val, isSet: true}
}

func (v NullableEntityActionFieldOverviewResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntityActionFieldOverviewResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


