/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateEntityActionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEntityActionRequest{}

// CreateEntityActionRequest struct for CreateEntityActionRequest
type CreateEntityActionRequest struct {
	// Identifier used in URLs and by agents; unique per template. Lowercase letters, digits and underscores, starting with a letter.
	Slug string `json:"slug"`
	// Label shown in menus and dialogs
	Name string `json:"name"`
	// What the action does, shown in the dialog
	Description NullableString `json:"description,omitempty"`
	// Material icon name
	Icon NullableString `json:"icon,omitempty"`
	// Conditions on the record's current values that must all hold for the action to be available. Omit or send an empty list for an action that is always available.
	Precondition []EntityRulePredicate `json:"precondition,omitempty"`
	// Values the operator is asked for, in dialog order. Each attribute may appear once and must not also be a preset.
	Fields []EntityActionField `json:"fields,omitempty"`
	// Values written silently on execution. Each attribute may appear once and must not also be a field.
	Presets []EntityActionPreset `json:"presets,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateEntityActionRequest CreateEntityActionRequest

// NewCreateEntityActionRequest instantiates a new CreateEntityActionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEntityActionRequest(slug string, name string) *CreateEntityActionRequest {
	this := CreateEntityActionRequest{}
	this.Slug = slug
	this.Name = name
	return &this
}

// NewCreateEntityActionRequestWithDefaults instantiates a new CreateEntityActionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEntityActionRequestWithDefaults() *CreateEntityActionRequest {
	this := CreateEntityActionRequest{}
	return &this
}

// GetSlug returns the Slug field value
func (o *CreateEntityActionRequest) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *CreateEntityActionRequest) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *CreateEntityActionRequest) SetSlug(v string) {
	o.Slug = v
}

// GetName returns the Name field value
func (o *CreateEntityActionRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateEntityActionRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateEntityActionRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateEntityActionRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateEntityActionRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateEntityActionRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *CreateEntityActionRequest) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *CreateEntityActionRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *CreateEntityActionRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetIcon returns the Icon field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateEntityActionRequest) GetIcon() string {
	if o == nil || IsNil(o.Icon.Get()) {
		var ret string
		return ret
	}
	return *o.Icon.Get()
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateEntityActionRequest) GetIconOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Icon.Get(), o.Icon.IsSet()
}

// HasIcon returns a boolean if a field has been set.
func (o *CreateEntityActionRequest) HasIcon() bool {
	if o != nil && o.Icon.IsSet() {
		return true
	}

	return false
}

// SetIcon gets a reference to the given NullableString and assigns it to the Icon field.
func (o *CreateEntityActionRequest) SetIcon(v string) {
	o.Icon.Set(&v)
}
// SetIconNil sets the value for Icon to be an explicit nil
func (o *CreateEntityActionRequest) SetIconNil() {
	o.Icon.Set(nil)
}

// UnsetIcon ensures that no value is present for Icon, not even an explicit nil
func (o *CreateEntityActionRequest) UnsetIcon() {
	o.Icon.Unset()
}

// GetPrecondition returns the Precondition field value if set, zero value otherwise.
func (o *CreateEntityActionRequest) GetPrecondition() []EntityRulePredicate {
	if o == nil || IsNil(o.Precondition) {
		var ret []EntityRulePredicate
		return ret
	}
	return o.Precondition
}

// GetPreconditionOk returns a tuple with the Precondition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEntityActionRequest) GetPreconditionOk() ([]EntityRulePredicate, bool) {
	if o == nil || IsNil(o.Precondition) {
		return nil, false
	}
	return o.Precondition, true
}

// HasPrecondition returns a boolean if a field has been set.
func (o *CreateEntityActionRequest) HasPrecondition() bool {
	if o != nil && !IsNil(o.Precondition) {
		return true
	}

	return false
}

// SetPrecondition gets a reference to the given []EntityRulePredicate and assigns it to the Precondition field.
func (o *CreateEntityActionRequest) SetPrecondition(v []EntityRulePredicate) {
	o.Precondition = v
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *CreateEntityActionRequest) GetFields() []EntityActionField {
	if o == nil || IsNil(o.Fields) {
		var ret []EntityActionField
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEntityActionRequest) GetFieldsOk() ([]EntityActionField, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *CreateEntityActionRequest) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given []EntityActionField and assigns it to the Fields field.
func (o *CreateEntityActionRequest) SetFields(v []EntityActionField) {
	o.Fields = v
}

// GetPresets returns the Presets field value if set, zero value otherwise.
func (o *CreateEntityActionRequest) GetPresets() []EntityActionPreset {
	if o == nil || IsNil(o.Presets) {
		var ret []EntityActionPreset
		return ret
	}
	return o.Presets
}

// GetPresetsOk returns a tuple with the Presets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEntityActionRequest) GetPresetsOk() ([]EntityActionPreset, bool) {
	if o == nil || IsNil(o.Presets) {
		return nil, false
	}
	return o.Presets, true
}

// HasPresets returns a boolean if a field has been set.
func (o *CreateEntityActionRequest) HasPresets() bool {
	if o != nil && !IsNil(o.Presets) {
		return true
	}

	return false
}

// SetPresets gets a reference to the given []EntityActionPreset and assigns it to the Presets field.
func (o *CreateEntityActionRequest) SetPresets(v []EntityActionPreset) {
	o.Presets = v
}

func (o CreateEntityActionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEntityActionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["slug"] = o.Slug
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Icon.IsSet() {
		toSerialize["icon"] = o.Icon.Get()
	}
	if !IsNil(o.Precondition) {
		toSerialize["precondition"] = o.Precondition
	}
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}
	if !IsNil(o.Presets) {
		toSerialize["presets"] = o.Presets
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateEntityActionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"slug",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateEntityActionRequest := _CreateEntityActionRequest{}

	err = json.Unmarshal(data, &varCreateEntityActionRequest)

	if err != nil {
		return err
	}

	*o = CreateEntityActionRequest(varCreateEntityActionRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "slug")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "icon")
		delete(additionalProperties, "precondition")
		delete(additionalProperties, "fields")
		delete(additionalProperties, "presets")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateEntityActionRequest struct {
	value *CreateEntityActionRequest
	isSet bool
}

func (v NullableCreateEntityActionRequest) Get() *CreateEntityActionRequest {
	return v.value
}

func (v *NullableCreateEntityActionRequest) Set(val *CreateEntityActionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEntityActionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEntityActionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEntityActionRequest(val *CreateEntityActionRequest) *NullableCreateEntityActionRequest {
	return &NullableCreateEntityActionRequest{value: val, isSet: true}
}

func (v NullableCreateEntityActionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEntityActionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


