/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
)

// checks if the ListTemplates200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListTemplates200Response{}

// ListTemplates200Response struct for ListTemplates200Response
type ListTemplates200Response struct {
	Data []TemplateResponse `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListTemplates200Response ListTemplates200Response

// NewListTemplates200Response instantiates a new ListTemplates200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListTemplates200Response() *ListTemplates200Response {
	this := ListTemplates200Response{}
	return &this
}

// NewListTemplates200ResponseWithDefaults instantiates a new ListTemplates200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListTemplates200ResponseWithDefaults() *ListTemplates200Response {
	this := ListTemplates200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListTemplates200Response) GetData() []TemplateResponse {
	if o == nil || IsNil(o.Data) {
		var ret []TemplateResponse
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListTemplates200Response) GetDataOk() ([]TemplateResponse, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListTemplates200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []TemplateResponse and assigns it to the Data field.
func (o *ListTemplates200Response) SetData(v []TemplateResponse) {
	o.Data = v
}

func (o ListTemplates200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListTemplates200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListTemplates200Response) UnmarshalJSON(data []byte) (err error) {
	varListTemplates200Response := _ListTemplates200Response{}

	err = json.Unmarshal(data, &varListTemplates200Response)

	if err != nil {
		return err
	}

	*o = ListTemplates200Response(varListTemplates200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListTemplates200Response struct {
	value *ListTemplates200Response
	isSet bool
}

func (v NullableListTemplates200Response) Get() *ListTemplates200Response {
	return v.value
}

func (v *NullableListTemplates200Response) Set(val *ListTemplates200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListTemplates200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListTemplates200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListTemplates200Response(val *ListTemplates200Response) *NullableListTemplates200Response {
	return &NullableListTemplates200Response{value: val, isSet: true}
}

func (v NullableListTemplates200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListTemplates200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


