/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the AggregateEntitiesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AggregateEntitiesRequest{}

// AggregateEntitiesRequest Which records to reduce, how to group them, and which reduces to compute per group.
type AggregateEntitiesRequest struct {
	// Narrows the records before grouping. Same grammar as the search endpoint: Filter groups: clauses inside a group are AND-ed, groups are OR-ed. `[]` applies no filter, `[[a, b]]` is `a AND b`, `[[a], [b, c]]` is `a OR (b AND c)`. Each clause is `{field, operator, value}` — see the `EntityFilter` schema for the shape. Unknown fields, operators that do not fit the field, malformed values, and reference paths into a template you cannot view are refused with 400/403.
	FilterGroups [][]EntityFilter `json:"filter_groups,omitempty"`
	// Attribute slugs or UUIDs to group by, at most 3. Lists, references, strings, numbers, booleans and dates can be keys; metrics, markdown, files and images cannot. Empty groups the whole filtered set into one row.
	GroupBy []string `json:"group_by,omitempty"`
	// Reduces computed for every group, reported back in this order. `count` takes no field; `sum` and `avg` need a number attribute; `min` and `max` accept number, date and datetime attributes.
	Aggregations []AggregateEntitiesRequestAggregationsInner `json:"aggregations"`
	// Maximum number of groups returned (1-100). The response says whether more groups exist.
	Limit *int32 `json:"limit,omitempty"`
	// Substring query matched across the template's attributes, exactly as the search endpoint's global_search, so group counts agree with search totals.
	GlobalSearch NullableString `json:"global_search,omitempty"`
	// `aggregate` (default) ranks groups by the first aggregation descending, nulls last, then by key. `key` lays groups out by their key: list attributes follow the list-item order, other attributes sort by label or value ascending, and the no-value group comes last. Use `key` to render records in sections, `aggregate` for top-N questions.
	Order *string `json:"order,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AggregateEntitiesRequest AggregateEntitiesRequest

// NewAggregateEntitiesRequest instantiates a new AggregateEntitiesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAggregateEntitiesRequest(aggregations []AggregateEntitiesRequestAggregationsInner) *AggregateEntitiesRequest {
	this := AggregateEntitiesRequest{}
	this.Aggregations = aggregations
	var limit int32 = 50
	this.Limit = &limit
	var order string = "aggregate"
	this.Order = &order
	return &this
}

// NewAggregateEntitiesRequestWithDefaults instantiates a new AggregateEntitiesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAggregateEntitiesRequestWithDefaults() *AggregateEntitiesRequest {
	this := AggregateEntitiesRequest{}
	var limit int32 = 50
	this.Limit = &limit
	var order string = "aggregate"
	this.Order = &order
	return &this
}

// GetFilterGroups returns the FilterGroups field value if set, zero value otherwise.
func (o *AggregateEntitiesRequest) GetFilterGroups() [][]EntityFilter {
	if o == nil || IsNil(o.FilterGroups) {
		var ret [][]EntityFilter
		return ret
	}
	return o.FilterGroups
}

// GetFilterGroupsOk returns a tuple with the FilterGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregateEntitiesRequest) GetFilterGroupsOk() ([][]EntityFilter, bool) {
	if o == nil || IsNil(o.FilterGroups) {
		return nil, false
	}
	return o.FilterGroups, true
}

// HasFilterGroups returns a boolean if a field has been set.
func (o *AggregateEntitiesRequest) HasFilterGroups() bool {
	if o != nil && !IsNil(o.FilterGroups) {
		return true
	}

	return false
}

// SetFilterGroups gets a reference to the given [][]EntityFilter and assigns it to the FilterGroups field.
func (o *AggregateEntitiesRequest) SetFilterGroups(v [][]EntityFilter) {
	o.FilterGroups = v
}

// GetGroupBy returns the GroupBy field value if set, zero value otherwise.
func (o *AggregateEntitiesRequest) GetGroupBy() []string {
	if o == nil || IsNil(o.GroupBy) {
		var ret []string
		return ret
	}
	return o.GroupBy
}

// GetGroupByOk returns a tuple with the GroupBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregateEntitiesRequest) GetGroupByOk() ([]string, bool) {
	if o == nil || IsNil(o.GroupBy) {
		return nil, false
	}
	return o.GroupBy, true
}

// HasGroupBy returns a boolean if a field has been set.
func (o *AggregateEntitiesRequest) HasGroupBy() bool {
	if o != nil && !IsNil(o.GroupBy) {
		return true
	}

	return false
}

// SetGroupBy gets a reference to the given []string and assigns it to the GroupBy field.
func (o *AggregateEntitiesRequest) SetGroupBy(v []string) {
	o.GroupBy = v
}

// GetAggregations returns the Aggregations field value
func (o *AggregateEntitiesRequest) GetAggregations() []AggregateEntitiesRequestAggregationsInner {
	if o == nil {
		var ret []AggregateEntitiesRequestAggregationsInner
		return ret
	}

	return o.Aggregations
}

// GetAggregationsOk returns a tuple with the Aggregations field value
// and a boolean to check if the value has been set.
func (o *AggregateEntitiesRequest) GetAggregationsOk() ([]AggregateEntitiesRequestAggregationsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Aggregations, true
}

// SetAggregations sets field value
func (o *AggregateEntitiesRequest) SetAggregations(v []AggregateEntitiesRequestAggregationsInner) {
	o.Aggregations = v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *AggregateEntitiesRequest) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregateEntitiesRequest) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *AggregateEntitiesRequest) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *AggregateEntitiesRequest) SetLimit(v int32) {
	o.Limit = &v
}

// GetGlobalSearch returns the GlobalSearch field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AggregateEntitiesRequest) GetGlobalSearch() string {
	if o == nil || IsNil(o.GlobalSearch.Get()) {
		var ret string
		return ret
	}
	return *o.GlobalSearch.Get()
}

// GetGlobalSearchOk returns a tuple with the GlobalSearch field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AggregateEntitiesRequest) GetGlobalSearchOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GlobalSearch.Get(), o.GlobalSearch.IsSet()
}

// HasGlobalSearch returns a boolean if a field has been set.
func (o *AggregateEntitiesRequest) HasGlobalSearch() bool {
	if o != nil && o.GlobalSearch.IsSet() {
		return true
	}

	return false
}

// SetGlobalSearch gets a reference to the given NullableString and assigns it to the GlobalSearch field.
func (o *AggregateEntitiesRequest) SetGlobalSearch(v string) {
	o.GlobalSearch.Set(&v)
}
// SetGlobalSearchNil sets the value for GlobalSearch to be an explicit nil
func (o *AggregateEntitiesRequest) SetGlobalSearchNil() {
	o.GlobalSearch.Set(nil)
}

// UnsetGlobalSearch ensures that no value is present for GlobalSearch, not even an explicit nil
func (o *AggregateEntitiesRequest) UnsetGlobalSearch() {
	o.GlobalSearch.Unset()
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *AggregateEntitiesRequest) GetOrder() string {
	if o == nil || IsNil(o.Order) {
		var ret string
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregateEntitiesRequest) GetOrderOk() (*string, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *AggregateEntitiesRequest) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given string and assigns it to the Order field.
func (o *AggregateEntitiesRequest) SetOrder(v string) {
	o.Order = &v
}

func (o AggregateEntitiesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AggregateEntitiesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FilterGroups) {
		toSerialize["filter_groups"] = o.FilterGroups
	}
	if !IsNil(o.GroupBy) {
		toSerialize["group_by"] = o.GroupBy
	}
	toSerialize["aggregations"] = o.Aggregations
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if o.GlobalSearch.IsSet() {
		toSerialize["global_search"] = o.GlobalSearch.Get()
	}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AggregateEntitiesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"aggregations",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAggregateEntitiesRequest := _AggregateEntitiesRequest{}

	err = json.Unmarshal(data, &varAggregateEntitiesRequest)

	if err != nil {
		return err
	}

	*o = AggregateEntitiesRequest(varAggregateEntitiesRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "filter_groups")
		delete(additionalProperties, "group_by")
		delete(additionalProperties, "aggregations")
		delete(additionalProperties, "limit")
		delete(additionalProperties, "global_search")
		delete(additionalProperties, "order")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAggregateEntitiesRequest struct {
	value *AggregateEntitiesRequest
	isSet bool
}

func (v NullableAggregateEntitiesRequest) Get() *AggregateEntitiesRequest {
	return v.value
}

func (v *NullableAggregateEntitiesRequest) Set(val *AggregateEntitiesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAggregateEntitiesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAggregateEntitiesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAggregateEntitiesRequest(val *AggregateEntitiesRequest) *NullableAggregateEntitiesRequest {
	return &NullableAggregateEntitiesRequest{value: val, isSet: true}
}

func (v NullableAggregateEntitiesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAggregateEntitiesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


