/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateAutomationRequestActionsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAutomationRequestActionsInner{}

// CreateAutomationRequestActionsInner struct for CreateAutomationRequestActionsInner
type CreateAutomationRequestActionsInner struct {
	Type string `json:"type"`
	Config map[string]interface{} `json:"config"`
	AdditionalProperties map[string]interface{}
}

type _CreateAutomationRequestActionsInner CreateAutomationRequestActionsInner

// NewCreateAutomationRequestActionsInner instantiates a new CreateAutomationRequestActionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAutomationRequestActionsInner(type_ string, config map[string]interface{}) *CreateAutomationRequestActionsInner {
	this := CreateAutomationRequestActionsInner{}
	this.Type = type_
	this.Config = config
	return &this
}

// NewCreateAutomationRequestActionsInnerWithDefaults instantiates a new CreateAutomationRequestActionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAutomationRequestActionsInnerWithDefaults() *CreateAutomationRequestActionsInner {
	this := CreateAutomationRequestActionsInner{}
	return &this
}

// GetType returns the Type field value
func (o *CreateAutomationRequestActionsInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateAutomationRequestActionsInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateAutomationRequestActionsInner) SetType(v string) {
	o.Type = v
}

// GetConfig returns the Config field value
func (o *CreateAutomationRequestActionsInner) GetConfig() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *CreateAutomationRequestActionsInner) GetConfigOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Config, true
}

// SetConfig sets field value
func (o *CreateAutomationRequestActionsInner) SetConfig(v map[string]interface{}) {
	o.Config = v
}

func (o CreateAutomationRequestActionsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAutomationRequestActionsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["config"] = o.Config

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateAutomationRequestActionsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"config",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAutomationRequestActionsInner := _CreateAutomationRequestActionsInner{}

	err = json.Unmarshal(data, &varCreateAutomationRequestActionsInner)

	if err != nil {
		return err
	}

	*o = CreateAutomationRequestActionsInner(varCreateAutomationRequestActionsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "config")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateAutomationRequestActionsInner struct {
	value *CreateAutomationRequestActionsInner
	isSet bool
}

func (v NullableCreateAutomationRequestActionsInner) Get() *CreateAutomationRequestActionsInner {
	return v.value
}

func (v *NullableCreateAutomationRequestActionsInner) Set(val *CreateAutomationRequestActionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAutomationRequestActionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAutomationRequestActionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAutomationRequestActionsInner(val *CreateAutomationRequestActionsInner) *NullableCreateAutomationRequestActionsInner {
	return &NullableCreateAutomationRequestActionsInner{value: val, isSet: true}
}

func (v NullableCreateAutomationRequestActionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAutomationRequestActionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


