/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// AggregateEntitiesGroupKeyInnerValue - The stored value: a list item id, an entity id, a string, a number, a boolean, or an RFC 3339 date. Null groups the records that have no value.
type AggregateEntitiesGroupKeyInnerValue struct {
	Bool *bool
	Float32 *float32
	String *string
}

// boolAsAggregateEntitiesGroupKeyInnerValue is a convenience function that returns bool wrapped in AggregateEntitiesGroupKeyInnerValue
func BoolAsAggregateEntitiesGroupKeyInnerValue(v *bool) AggregateEntitiesGroupKeyInnerValue {
	return AggregateEntitiesGroupKeyInnerValue{
		Bool: v,
	}
}

// float32AsAggregateEntitiesGroupKeyInnerValue is a convenience function that returns float32 wrapped in AggregateEntitiesGroupKeyInnerValue
func Float32AsAggregateEntitiesGroupKeyInnerValue(v *float32) AggregateEntitiesGroupKeyInnerValue {
	return AggregateEntitiesGroupKeyInnerValue{
		Float32: v,
	}
}

// stringAsAggregateEntitiesGroupKeyInnerValue is a convenience function that returns string wrapped in AggregateEntitiesGroupKeyInnerValue
func StringAsAggregateEntitiesGroupKeyInnerValue(v *string) AggregateEntitiesGroupKeyInnerValue {
	return AggregateEntitiesGroupKeyInnerValue{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *AggregateEntitiesGroupKeyInnerValue) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into Bool
	err = newStrictDecoder(data).Decode(&dst.Bool)
	if err == nil {
		jsonBool, _ := json.Marshal(dst.Bool)
		if string(jsonBool) == "{}" { // empty struct
			dst.Bool = nil
		} else {
			if err = validator.Validate(dst.Bool); err != nil {
				dst.Bool = nil
			} else {
				match++
			}
		}
	} else {
		dst.Bool = nil
	}

	// try to unmarshal data into Float32
	err = newStrictDecoder(data).Decode(&dst.Float32)
	if err == nil {
		jsonFloat32, _ := json.Marshal(dst.Float32)
		if string(jsonFloat32) == "{}" { // empty struct
			dst.Float32 = nil
		} else {
			if err = validator.Validate(dst.Float32); err != nil {
				dst.Float32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Float32 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Bool = nil
		dst.Float32 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(AggregateEntitiesGroupKeyInnerValue)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(AggregateEntitiesGroupKeyInnerValue)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src AggregateEntitiesGroupKeyInnerValue) MarshalJSON() ([]byte, error) {
	if src.Bool != nil {
		return json.Marshal(&src.Bool)
	}

	if src.Float32 != nil {
		return json.Marshal(&src.Float32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *AggregateEntitiesGroupKeyInnerValue) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Bool != nil {
		return obj.Bool
	}

	if obj.Float32 != nil {
		return obj.Float32
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj AggregateEntitiesGroupKeyInnerValue) GetActualInstanceValue() (interface{}) {
	if obj.Bool != nil {
		return *obj.Bool
	}

	if obj.Float32 != nil {
		return *obj.Float32
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableAggregateEntitiesGroupKeyInnerValue struct {
	value *AggregateEntitiesGroupKeyInnerValue
	isSet bool
}

func (v NullableAggregateEntitiesGroupKeyInnerValue) Get() *AggregateEntitiesGroupKeyInnerValue {
	return v.value
}

func (v *NullableAggregateEntitiesGroupKeyInnerValue) Set(val *AggregateEntitiesGroupKeyInnerValue) {
	v.value = val
	v.isSet = true
}

func (v NullableAggregateEntitiesGroupKeyInnerValue) IsSet() bool {
	return v.isSet
}

func (v *NullableAggregateEntitiesGroupKeyInnerValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAggregateEntitiesGroupKeyInnerValue(val *AggregateEntitiesGroupKeyInnerValue) *NullableAggregateEntitiesGroupKeyInnerValue {
	return &NullableAggregateEntitiesGroupKeyInnerValue{value: val, isSet: true}
}

func (v NullableAggregateEntitiesGroupKeyInnerValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAggregateEntitiesGroupKeyInnerValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


