/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
)

// checks if the TemplateEntityCountResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateEntityCountResponse{}

// TemplateEntityCountResponse Entity count for a template
type TemplateEntityCountResponse struct {
	TemplateId *string `json:"template_id,omitempty"`
	EntityCount *int32 `json:"entity_count,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TemplateEntityCountResponse TemplateEntityCountResponse

// NewTemplateEntityCountResponse instantiates a new TemplateEntityCountResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateEntityCountResponse() *TemplateEntityCountResponse {
	this := TemplateEntityCountResponse{}
	return &this
}

// NewTemplateEntityCountResponseWithDefaults instantiates a new TemplateEntityCountResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateEntityCountResponseWithDefaults() *TemplateEntityCountResponse {
	this := TemplateEntityCountResponse{}
	return &this
}

// GetTemplateId returns the TemplateId field value if set, zero value otherwise.
func (o *TemplateEntityCountResponse) GetTemplateId() string {
	if o == nil || IsNil(o.TemplateId) {
		var ret string
		return ret
	}
	return *o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateEntityCountResponse) GetTemplateIdOk() (*string, bool) {
	if o == nil || IsNil(o.TemplateId) {
		return nil, false
	}
	return o.TemplateId, true
}

// HasTemplateId returns a boolean if a field has been set.
func (o *TemplateEntityCountResponse) HasTemplateId() bool {
	if o != nil && !IsNil(o.TemplateId) {
		return true
	}

	return false
}

// SetTemplateId gets a reference to the given string and assigns it to the TemplateId field.
func (o *TemplateEntityCountResponse) SetTemplateId(v string) {
	o.TemplateId = &v
}

// GetEntityCount returns the EntityCount field value if set, zero value otherwise.
func (o *TemplateEntityCountResponse) GetEntityCount() int32 {
	if o == nil || IsNil(o.EntityCount) {
		var ret int32
		return ret
	}
	return *o.EntityCount
}

// GetEntityCountOk returns a tuple with the EntityCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateEntityCountResponse) GetEntityCountOk() (*int32, bool) {
	if o == nil || IsNil(o.EntityCount) {
		return nil, false
	}
	return o.EntityCount, true
}

// HasEntityCount returns a boolean if a field has been set.
func (o *TemplateEntityCountResponse) HasEntityCount() bool {
	if o != nil && !IsNil(o.EntityCount) {
		return true
	}

	return false
}

// SetEntityCount gets a reference to the given int32 and assigns it to the EntityCount field.
func (o *TemplateEntityCountResponse) SetEntityCount(v int32) {
	o.EntityCount = &v
}

func (o TemplateEntityCountResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateEntityCountResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TemplateId) {
		toSerialize["template_id"] = o.TemplateId
	}
	if !IsNil(o.EntityCount) {
		toSerialize["entity_count"] = o.EntityCount
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TemplateEntityCountResponse) UnmarshalJSON(data []byte) (err error) {
	varTemplateEntityCountResponse := _TemplateEntityCountResponse{}

	err = json.Unmarshal(data, &varTemplateEntityCountResponse)

	if err != nil {
		return err
	}

	*o = TemplateEntityCountResponse(varTemplateEntityCountResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "template_id")
		delete(additionalProperties, "entity_count")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTemplateEntityCountResponse struct {
	value *TemplateEntityCountResponse
	isSet bool
}

func (v NullableTemplateEntityCountResponse) Get() *TemplateEntityCountResponse {
	return v.value
}

func (v *NullableTemplateEntityCountResponse) Set(val *TemplateEntityCountResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateEntityCountResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateEntityCountResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateEntityCountResponse(val *TemplateEntityCountResponse) *NullableTemplateEntityCountResponse {
	return &NullableTemplateEntityCountResponse{value: val, isSet: true}
}

func (v NullableTemplateEntityCountResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateEntityCountResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


