/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateEntityRuleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEntityRuleRequest{}

// CreateEntityRuleRequest struct for CreateEntityRuleRequest
type CreateEntityRuleRequest struct {
	// Short name shown in the template editor
	Name string `json:"name"`
	// Text returned to the client when the rule is violated
	Message string `json:"message"`
	// Conditions that activate the rule; all must hold. Omit or send an empty list for an unconditional rule (a plain required field).
	When []EntityRulePredicate `json:"when,omitempty"`
	// Constraints that must hold once the rule is active. `is_not_empty` on an attribute is the \"required\" constraint.
	Then []EntityRulePredicate `json:"then"`
	AdditionalProperties map[string]interface{}
}

type _CreateEntityRuleRequest CreateEntityRuleRequest

// NewCreateEntityRuleRequest instantiates a new CreateEntityRuleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEntityRuleRequest(name string, message string, then []EntityRulePredicate) *CreateEntityRuleRequest {
	this := CreateEntityRuleRequest{}
	this.Name = name
	this.Message = message
	this.Then = then
	return &this
}

// NewCreateEntityRuleRequestWithDefaults instantiates a new CreateEntityRuleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEntityRuleRequestWithDefaults() *CreateEntityRuleRequest {
	this := CreateEntityRuleRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateEntityRuleRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateEntityRuleRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateEntityRuleRequest) SetName(v string) {
	o.Name = v
}

// GetMessage returns the Message field value
func (o *CreateEntityRuleRequest) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *CreateEntityRuleRequest) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *CreateEntityRuleRequest) SetMessage(v string) {
	o.Message = v
}

// GetWhen returns the When field value if set, zero value otherwise.
func (o *CreateEntityRuleRequest) GetWhen() []EntityRulePredicate {
	if o == nil || IsNil(o.When) {
		var ret []EntityRulePredicate
		return ret
	}
	return o.When
}

// GetWhenOk returns a tuple with the When field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEntityRuleRequest) GetWhenOk() ([]EntityRulePredicate, bool) {
	if o == nil || IsNil(o.When) {
		return nil, false
	}
	return o.When, true
}

// HasWhen returns a boolean if a field has been set.
func (o *CreateEntityRuleRequest) HasWhen() bool {
	if o != nil && !IsNil(o.When) {
		return true
	}

	return false
}

// SetWhen gets a reference to the given []EntityRulePredicate and assigns it to the When field.
func (o *CreateEntityRuleRequest) SetWhen(v []EntityRulePredicate) {
	o.When = v
}

// GetThen returns the Then field value
func (o *CreateEntityRuleRequest) GetThen() []EntityRulePredicate {
	if o == nil {
		var ret []EntityRulePredicate
		return ret
	}

	return o.Then
}

// GetThenOk returns a tuple with the Then field value
// and a boolean to check if the value has been set.
func (o *CreateEntityRuleRequest) GetThenOk() ([]EntityRulePredicate, bool) {
	if o == nil {
		return nil, false
	}
	return o.Then, true
}

// SetThen sets field value
func (o *CreateEntityRuleRequest) SetThen(v []EntityRulePredicate) {
	o.Then = v
}

func (o CreateEntityRuleRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEntityRuleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["message"] = o.Message
	if !IsNil(o.When) {
		toSerialize["when"] = o.When
	}
	toSerialize["then"] = o.Then

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateEntityRuleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"message",
		"then",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateEntityRuleRequest := _CreateEntityRuleRequest{}

	err = json.Unmarshal(data, &varCreateEntityRuleRequest)

	if err != nil {
		return err
	}

	*o = CreateEntityRuleRequest(varCreateEntityRuleRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "message")
		delete(additionalProperties, "when")
		delete(additionalProperties, "then")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateEntityRuleRequest struct {
	value *CreateEntityRuleRequest
	isSet bool
}

func (v NullableCreateEntityRuleRequest) Get() *CreateEntityRuleRequest {
	return v.value
}

func (v *NullableCreateEntityRuleRequest) Set(val *CreateEntityRuleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEntityRuleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEntityRuleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEntityRuleRequest(val *CreateEntityRuleRequest) *NullableCreateEntityRuleRequest {
	return &NullableCreateEntityRuleRequest{value: val, isSet: true}
}

func (v NullableCreateEntityRuleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEntityRuleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


