/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
)

// checks if the ListDashboards200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDashboards200Response{}

// ListDashboards200Response struct for ListDashboards200Response
type ListDashboards200Response struct {
	Data []DashboardResponse `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListDashboards200Response ListDashboards200Response

// NewListDashboards200Response instantiates a new ListDashboards200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDashboards200Response() *ListDashboards200Response {
	this := ListDashboards200Response{}
	return &this
}

// NewListDashboards200ResponseWithDefaults instantiates a new ListDashboards200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDashboards200ResponseWithDefaults() *ListDashboards200Response {
	this := ListDashboards200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListDashboards200Response) GetData() []DashboardResponse {
	if o == nil || IsNil(o.Data) {
		var ret []DashboardResponse
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListDashboards200Response) GetDataOk() ([]DashboardResponse, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListDashboards200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []DashboardResponse and assigns it to the Data field.
func (o *ListDashboards200Response) SetData(v []DashboardResponse) {
	o.Data = v
}

func (o ListDashboards200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDashboards200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListDashboards200Response) UnmarshalJSON(data []byte) (err error) {
	varListDashboards200Response := _ListDashboards200Response{}

	err = json.Unmarshal(data, &varListDashboards200Response)

	if err != nil {
		return err
	}

	*o = ListDashboards200Response(varListDashboards200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListDashboards200Response struct {
	value *ListDashboards200Response
	isSet bool
}

func (v NullableListDashboards200Response) Get() *ListDashboards200Response {
	return v.value
}

func (v *NullableListDashboards200Response) Set(val *ListDashboards200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListDashboards200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListDashboards200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDashboards200Response(val *ListDashboards200Response) *NullableListDashboards200Response {
	return &NullableListDashboards200Response{value: val, isSet: true}
}

func (v NullableListDashboards200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDashboards200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


