/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
)

// checks if the ListAutomationExecutions200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAutomationExecutions200Response{}

// ListAutomationExecutions200Response struct for ListAutomationExecutions200Response
type ListAutomationExecutions200Response struct {
	// Array of execution records
	Data []AutomationExecutionResponse `json:"data,omitempty"`
	// Total count of execution records matching filters
	Total *int32 `json:"total,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListAutomationExecutions200Response ListAutomationExecutions200Response

// NewListAutomationExecutions200Response instantiates a new ListAutomationExecutions200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAutomationExecutions200Response() *ListAutomationExecutions200Response {
	this := ListAutomationExecutions200Response{}
	return &this
}

// NewListAutomationExecutions200ResponseWithDefaults instantiates a new ListAutomationExecutions200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAutomationExecutions200ResponseWithDefaults() *ListAutomationExecutions200Response {
	this := ListAutomationExecutions200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListAutomationExecutions200Response) GetData() []AutomationExecutionResponse {
	if o == nil || IsNil(o.Data) {
		var ret []AutomationExecutionResponse
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAutomationExecutions200Response) GetDataOk() ([]AutomationExecutionResponse, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListAutomationExecutions200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []AutomationExecutionResponse and assigns it to the Data field.
func (o *ListAutomationExecutions200Response) SetData(v []AutomationExecutionResponse) {
	o.Data = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ListAutomationExecutions200Response) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAutomationExecutions200Response) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ListAutomationExecutions200Response) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *ListAutomationExecutions200Response) SetTotal(v int32) {
	o.Total = &v
}

func (o ListAutomationExecutions200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAutomationExecutions200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListAutomationExecutions200Response) UnmarshalJSON(data []byte) (err error) {
	varListAutomationExecutions200Response := _ListAutomationExecutions200Response{}

	err = json.Unmarshal(data, &varListAutomationExecutions200Response)

	if err != nil {
		return err
	}

	*o = ListAutomationExecutions200Response(varListAutomationExecutions200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "total")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListAutomationExecutions200Response struct {
	value *ListAutomationExecutions200Response
	isSet bool
}

func (v NullableListAutomationExecutions200Response) Get() *ListAutomationExecutions200Response {
	return v.value
}

func (v *NullableListAutomationExecutions200Response) Set(val *ListAutomationExecutions200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListAutomationExecutions200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListAutomationExecutions200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAutomationExecutions200Response(val *ListAutomationExecutions200Response) *NullableListAutomationExecutions200Response {
	return &NullableListAutomationExecutions200Response{value: val, isSet: true}
}

func (v NullableListAutomationExecutions200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAutomationExecutions200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


