/*
Omnismith API

API Documentation for Omnismith

API version: 1.0.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnismithsdk

import (
	"encoding/json"
)

// checks if the UpdateAttributeRequestReferenceConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAttributeRequestReferenceConfig{}

// UpdateAttributeRequestReferenceConfig string, target_attribute_id: string}|null
type UpdateAttributeRequestReferenceConfig struct {
	TargetTemplateId *string `json:"target_template_id,omitempty"`
	TargetAttributeId *string `json:"target_attribute_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateAttributeRequestReferenceConfig UpdateAttributeRequestReferenceConfig

// NewUpdateAttributeRequestReferenceConfig instantiates a new UpdateAttributeRequestReferenceConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAttributeRequestReferenceConfig() *UpdateAttributeRequestReferenceConfig {
	this := UpdateAttributeRequestReferenceConfig{}
	return &this
}

// NewUpdateAttributeRequestReferenceConfigWithDefaults instantiates a new UpdateAttributeRequestReferenceConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAttributeRequestReferenceConfigWithDefaults() *UpdateAttributeRequestReferenceConfig {
	this := UpdateAttributeRequestReferenceConfig{}
	return &this
}

// GetTargetTemplateId returns the TargetTemplateId field value if set, zero value otherwise.
func (o *UpdateAttributeRequestReferenceConfig) GetTargetTemplateId() string {
	if o == nil || IsNil(o.TargetTemplateId) {
		var ret string
		return ret
	}
	return *o.TargetTemplateId
}

// GetTargetTemplateIdOk returns a tuple with the TargetTemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAttributeRequestReferenceConfig) GetTargetTemplateIdOk() (*string, bool) {
	if o == nil || IsNil(o.TargetTemplateId) {
		return nil, false
	}
	return o.TargetTemplateId, true
}

// HasTargetTemplateId returns a boolean if a field has been set.
func (o *UpdateAttributeRequestReferenceConfig) HasTargetTemplateId() bool {
	if o != nil && !IsNil(o.TargetTemplateId) {
		return true
	}

	return false
}

// SetTargetTemplateId gets a reference to the given string and assigns it to the TargetTemplateId field.
func (o *UpdateAttributeRequestReferenceConfig) SetTargetTemplateId(v string) {
	o.TargetTemplateId = &v
}

// GetTargetAttributeId returns the TargetAttributeId field value if set, zero value otherwise.
func (o *UpdateAttributeRequestReferenceConfig) GetTargetAttributeId() string {
	if o == nil || IsNil(o.TargetAttributeId) {
		var ret string
		return ret
	}
	return *o.TargetAttributeId
}

// GetTargetAttributeIdOk returns a tuple with the TargetAttributeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAttributeRequestReferenceConfig) GetTargetAttributeIdOk() (*string, bool) {
	if o == nil || IsNil(o.TargetAttributeId) {
		return nil, false
	}
	return o.TargetAttributeId, true
}

// HasTargetAttributeId returns a boolean if a field has been set.
func (o *UpdateAttributeRequestReferenceConfig) HasTargetAttributeId() bool {
	if o != nil && !IsNil(o.TargetAttributeId) {
		return true
	}

	return false
}

// SetTargetAttributeId gets a reference to the given string and assigns it to the TargetAttributeId field.
func (o *UpdateAttributeRequestReferenceConfig) SetTargetAttributeId(v string) {
	o.TargetAttributeId = &v
}

func (o UpdateAttributeRequestReferenceConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAttributeRequestReferenceConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TargetTemplateId) {
		toSerialize["target_template_id"] = o.TargetTemplateId
	}
	if !IsNil(o.TargetAttributeId) {
		toSerialize["target_attribute_id"] = o.TargetAttributeId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateAttributeRequestReferenceConfig) UnmarshalJSON(data []byte) (err error) {
	varUpdateAttributeRequestReferenceConfig := _UpdateAttributeRequestReferenceConfig{}

	err = json.Unmarshal(data, &varUpdateAttributeRequestReferenceConfig)

	if err != nil {
		return err
	}

	*o = UpdateAttributeRequestReferenceConfig(varUpdateAttributeRequestReferenceConfig)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "target_template_id")
		delete(additionalProperties, "target_attribute_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateAttributeRequestReferenceConfig struct {
	value *UpdateAttributeRequestReferenceConfig
	isSet bool
}

func (v NullableUpdateAttributeRequestReferenceConfig) Get() *UpdateAttributeRequestReferenceConfig {
	return v.value
}

func (v *NullableUpdateAttributeRequestReferenceConfig) Set(val *UpdateAttributeRequestReferenceConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAttributeRequestReferenceConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAttributeRequestReferenceConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAttributeRequestReferenceConfig(val *UpdateAttributeRequestReferenceConfig) *NullableUpdateAttributeRequestReferenceConfig {
	return &NullableUpdateAttributeRequestReferenceConfig{value: val, isSet: true}
}

func (v NullableUpdateAttributeRequestReferenceConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAttributeRequestReferenceConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


